/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userController = require('./user.controller');
module.exports.addressController = require('./address.controller');
module.exports.bankController = require('./bank.controller');
module.exports.vendorUserController = require('./vendorUser.controller');
module.exports.vendorKycController = require('./vendorKyc.controller');
module.exports.categoriesController = require('./categories.controller');
module.exports.servicesController = require('./services.controller');
module.exports.vendorServiceController = require('./vendorService.controller');
module.exports.bookingsController = require('./bookings.controller');
module.exports.paymentsController = require('./payments.controller');
module.exports.reviewsController = require('./reviews.controller');
module.exports.chatsController = require('./chats.controller');
module.exports.messagesController = require('./messages.controller');
module.exports.notificationsController = require('./notifications.controller');
module.exports.supportTicketController = require('./supportTicket.controller');
module.exports.walletController = require('./wallet.controller');
module.exports.payoutsController = require('./payouts.controller');
module.exports.couponsController = require('./coupons.controller');
module.exports.bookingCouponsController = require('./bookingCoupons.controller');
module.exports.vendorAvailabilityController = require('./vendorAvailability.controller');
module.exports.bookingTrackingController = require('./bookingTracking.controller');
module.exports.favoriteVendorController = require('./favoriteVendor.controller');
module.exports.authController = require('./auth.controller');
