/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Address, User } from 'models';

export async function getAddressById(id, options = {}) {
  const address = await Address.findById(id, options.projection, options);
  return address;
}

export async function getOne(query, options = {}) {
  const address = await Address.findOne(query, options.projection, options);
  return address;
}

export async function getAddressList(filter, options = {}) {
  const address = await Address.find(filter, options.projection, options);
  return address;
}

export async function getAddressListWithPagination(filter, options = {}) {
  const address = await Address.paginate(filter, options);
  return address;
}

export async function createAddress(body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  const address = await Address.create(body);
  return address;
}

export async function updateAddress(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  const address = await Address.findOneAndUpdate(filter, body, options);
  return address;
}

export async function updateManyAddress(filter, body, options = {}) {
  const address = await Address.updateMany(filter, body, options);
  return address;
}

export async function removeAddress(filter) {
  const address = await Address.findOneAndRemove(filter);
  return address;
}

export async function removeManyAddress(filter) {
  const address = await Address.deleteMany(filter);
  return address;
}

export async function aggregateAddress(query) {
  const address = await Address.aggregate(query);
  return address;
}

export async function aggregateAddressWithPagination(query, options = {}) {
  const aggregate = Address.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const address = await Address.aggregatePaginate(aggregate, options);
  return address;
}
