/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Bank, VendorUser } from 'models';

export async function getBankById(id, options = {}) {
  const bank = await Bank.findById(id, options.projection, options);
  return bank;
}

export async function getOne(query, options = {}) {
  const bank = await Bank.findOne(query, options.projection, options);
  return bank;
}

export async function getBankList(filter, options = {}) {
  const bank = await Bank.find(filter, options.projection, options);
  return bank;
}

export async function getBankListWithPagination(filter, options = {}) {
  const bank = await Bank.paginate(filter, options);
  return bank;
}

export async function createBank(body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const bank = await Bank.create(body);
  return bank;
}

export async function updateBank(filter, body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const bank = await Bank.findOneAndUpdate(filter, body, options);
  return bank;
}

export async function updateManyBank(filter, body, options = {}) {
  const bank = await Bank.updateMany(filter, body, options);
  return bank;
}

export async function removeBank(filter) {
  const bank = await Bank.findOneAndRemove(filter);
  return bank;
}

export async function removeManyBank(filter) {
  const bank = await Bank.deleteMany(filter);
  return bank;
}

export async function aggregateBank(query) {
  const bank = await Bank.aggregate(query);
  return bank;
}

export async function aggregateBankWithPagination(query, options = {}) {
  const aggregate = Bank.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const bank = await Bank.aggregatePaginate(aggregate, options);
  return bank;
}
