/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { BookingCoupons, Bookings, Coupons } from 'models';

export async function getBookingCouponsById(id, options = {}) {
  const bookingCoupons = await BookingCoupons.findById(id, options.projection, options);
  return bookingCoupons;
}

export async function getOne(query, options = {}) {
  const bookingCoupons = await BookingCoupons.findOne(query, options.projection, options);
  return bookingCoupons;
}

export async function getBookingCouponsList(filter, options = {}) {
  const bookingCoupons = await BookingCoupons.find(filter, options.projection, options);
  return bookingCoupons;
}

export async function getBookingCouponsListWithPagination(filter, options = {}) {
  const bookingCoupons = await BookingCoupons.paginate(filter, options);
  return bookingCoupons;
}

export async function createBookingCoupons(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.couponId) {
    const couponId = await Coupons.findOne({ _id: body.couponId });
    if (!couponId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field couponId is not valid');
    }
  }
  const bookingCoupons = await BookingCoupons.create(body);
  return bookingCoupons;
}

export async function updateBookingCoupons(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.couponId) {
    const couponId = await Coupons.findOne({ _id: body.couponId });
    if (!couponId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field couponId is not valid');
    }
  }
  const bookingCoupons = await BookingCoupons.findOneAndUpdate(filter, body, options);
  return bookingCoupons;
}

export async function updateManyBookingCoupons(filter, body, options = {}) {
  const bookingCoupons = await BookingCoupons.updateMany(filter, body, options);
  return bookingCoupons;
}

export async function removeBookingCoupons(filter) {
  const bookingCoupons = await BookingCoupons.findOneAndRemove(filter);
  return bookingCoupons;
}

export async function removeManyBookingCoupons(filter) {
  const bookingCoupons = await BookingCoupons.deleteMany(filter);
  return bookingCoupons;
}

export async function aggregateBookingCoupons(query) {
  const bookingCoupons = await BookingCoupons.aggregate(query);
  return bookingCoupons;
}

export async function aggregateBookingCouponsWithPagination(query, options = {}) {
  const aggregate = BookingCoupons.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const bookingCoupons = await BookingCoupons.aggregatePaginate(aggregate, options);
  return bookingCoupons;
}
