/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Bookings, User, VendorUser, Services, VendorService, Address, VendorAvailability } from 'models';
import { EnumStatusOfBookings } from 'models/enum.model';

export async function getBookingsById(id, options = {}) {
  const bookings = await Bookings.findById(id, options.projection, options);
  return bookings;
}

export async function getOne(query, options = {}) {
  const bookings = await Bookings.findOne(query, options.projection, options);
  return bookings;
}

export async function getBookingsList(filter, options = {}) {
  const bookings = await Bookings.find(filter, options.projection, options);
  return bookings;
}

export async function getBookingsListWithPagination(filter, options = {}) {
  const bookings = await Bookings.paginate(filter, options);
  return bookings;
}

function formatTime(date) {
  let hours = date.getHours();
  let minutes = date.getMinutes();
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours %= 12;
  hours = hours || 12;
  minutes = minutes < 10 ? `0${minutes}` : minutes;
  return `${hours}:${minutes} ${ampm}`;
}

async function generateUniqueBookingId() {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let isUnique = false;
  let bookingId = '';
  while (!isUnique) {
    bookingId = '';
    for (let i = 0; i < 8; i += 1) {
      bookingId += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    // eslint-disable-next-line no-await-in-loop
    const existing = await Bookings.findOne({ bookingId });
    if (!existing) {
      isUnique = true;
    }
  }
  return bookingId;
}

export async function createBookings(body = {}) {
  // Automatically generate unique 8-character bookingId if not provided
  if (!body.bookingId) {
    // eslint-disable-next-line no-param-reassign
    body.bookingId = await generateUniqueBookingId();
  }

  // Automatically default bookingDate and bookingTime to current if not provided
  const now = new Date();
  if (!body.bookingDate) {
    // eslint-disable-next-line no-param-reassign
    body.bookingDate = now;
  } else {
    // eslint-disable-next-line no-param-reassign
    body.bookingDate = new Date(body.bookingDate);
  }

  let vendorAvailability = null;
  if (body.vendorId) {
    vendorAvailability = await VendorAvailability.findOne({ vendorId: body.vendorId, isDeleted: { $ne: true } });
  }

  // Automatically determine booking type & scheduling details from BE
  if (body.timeSlot || body.bookingType === 'schedule') {
    // eslint-disable-next-line no-param-reassign
    body.bookingType = 'schedule';
    // eslint-disable-next-line no-param-reassign
    body.bookingTime = body.timeSlot || body.bookingTime || formatTime(now);
  } else {
    // Vendor is on instant visit or default
    // eslint-disable-next-line no-param-reassign
    body.bookingType = (vendorAvailability && vendorAvailability.bookingOption) || 'instant';
    // eslint-disable-next-line no-param-reassign
    body.bookingTime = body.bookingTime || formatTime(now);
    if (body.bookingType === 'instant' && !body.estimatedArrival) {
      // eslint-disable-next-line no-param-reassign
      body.estimatedArrival = (vendorAvailability && vendorAvailability.instantArrivalEstimate) || '30-40 mins';
    }
  }

  if (!body.status) {
    // eslint-disable-next-line no-param-reassign
    body.status = EnumStatusOfBookings.PANDING;
  }

  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  if (body.vendorServiceId) {
    const vendorServiceId = await VendorService.findOne({ _id: body.vendorServiceId });
    if (!vendorServiceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorServiceId is not valid');
    }
  }
  if (body.addressId) {
    const addressId = await Address.findOne({ _id: body.addressId });
    if (!addressId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field addressId is not valid');
    }
  }

  // Verify multiple vendorServiceIds if passed
  if (body.vendorServiceIds && Array.isArray(body.vendorServiceIds)) {
    // eslint-disable-next-line no-restricted-syntax
    for (const vsId of body.vendorServiceIds) {
      // eslint-disable-next-line no-await-in-loop
      const exists = await VendorService.findOne({ _id: vsId });
      if (!exists) {
        throw new ApiError(httpStatus.BAD_REQUEST, `vendorServiceId ${vsId} is not valid`);
      }
    }
  }

  // Verify multiple serviceIds if passed
  if (body.serviceIds && Array.isArray(body.serviceIds)) {
    // eslint-disable-next-line no-restricted-syntax
    for (const sId of body.serviceIds) {
      // eslint-disable-next-line no-await-in-loop
      const exists = await Services.findOne({ _id: sId });
      if (!exists) {
        throw new ApiError(httpStatus.BAD_REQUEST, `serviceId ${sId} is not valid`);
      }
    }
  }

  // Auto-calculate pricing fields directly from selected services
  const queryConditions = [];
  if (body.vendorServiceId) {
    queryConditions.push({ _id: body.vendorServiceId });
  }
  if (body.vendorServiceIds && Array.isArray(body.vendorServiceIds)) {
    queryConditions.push({ _id: { $in: body.vendorServiceIds } });
  }
  if (body.vendorId && body.serviceIds && Array.isArray(body.serviceIds) && body.serviceIds.length > 0) {
    queryConditions.push({ vendorId: body.vendorId, serviceId: { $in: body.serviceIds } });
  }

  let vendorServices = [];
  if (queryConditions.length > 0) {
    vendorServices = await VendorService.find({
      $or: queryConditions,
      isDeleted: { $ne: true },
    });
  }

  let subtotal = 0;
  // eslint-disable-next-line no-restricted-syntax
  for (const vs of vendorServices) {
    if (vs.pricingType === 'fixed') {
      subtotal += vs.price || 0;
    }
  }

  // Calculate visit charge if coordinates are passed for visiting charge calculation
  let visitCharge = 0;
  if (body.latitude && body.longitude && body.vendorId) {
    const vendorUser = await VendorUser.findById(body.vendorId).populate('userId');
    if (vendorUser && vendorUser.userId && vendorUser.userId.location && vendorUser.userId.location.coordinates) {
      const lat1 = body.latitude;
      const lon1 = body.longitude;
      const [lon2, lat2] = vendorUser.userId.location.coordinates;

      const R = 6371; // Earth's radius in km
      const dLat = ((lat2 - lat1) * Math.PI) / 180;
      const dLon = ((lon2 - lon1) * Math.PI) / 180;
      const a =
        Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
      const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
      const distanceKm = R * c;

      if (vendorUser.visitCharges && Array.isArray(vendorUser.visitCharges)) {
        const matchedCharge = vendorUser.visitCharges.find(
          (vc) => distanceKm >= vc.minDistance && distanceKm <= vc.maxDistance
        );
        if (matchedCharge) {
          visitCharge = matchedCharge.charge || 0;
        }
      }
    }
  }

  subtotal += visitCharge;

  // eslint-disable-next-line no-param-reassign
  body.subtotal = subtotal;
  // eslint-disable-next-line no-param-reassign
  body.serviceFee = Math.round(subtotal * 0.05 * 100) / 100; // 5% service fee
  // eslint-disable-next-line no-param-reassign
  body.tax = Math.round(subtotal * 0.05 * 100) / 100; // 5% taxes
  // eslint-disable-next-line no-param-reassign
  body.totalAmount = Math.round((body.subtotal + body.serviceFee + body.tax) * 100) / 100;

  const bookings = await Bookings.create(body);
  return bookings;
}

export async function updateBookings(filter, body, options = {}) {
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  if (body.vendorServiceId) {
    const vendorServiceId = await VendorService.findOne({ _id: body.vendorServiceId });
    if (!vendorServiceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorServiceId is not valid');
    }
  }
  if (body.addressId) {
    const addressId = await Address.findOne({ _id: body.addressId });
    if (!addressId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field addressId is not valid');
    }
  }
  const bookings = await Bookings.findOneAndUpdate(filter, body, options);
  return bookings;
}

export async function updateManyBookings(filter, body, options = {}) {
  const bookings = await Bookings.updateMany(filter, body, options);
  return bookings;
}

export async function removeBookings(filter) {
  const bookings = await Bookings.findOneAndRemove(filter);
  return bookings;
}

export async function removeManyBookings(filter) {
  const bookings = await Bookings.deleteMany(filter);
  return bookings;
}

export async function aggregateBookings(query) {
  const bookings = await Bookings.aggregate(query);
  return bookings;
}

// export async function aggregateBookingsWithPagination(query, options = {}) {
//   const aggregate = Bookings.aggregate();
//   query.map((obj) => {
//     aggregate._pipeline.push(obj);
//   });
//   const bookings = await Bookings.aggregatePaginate(aggregate, options);
//   return bookings;
// }
