/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Bookings, User, VendorUser, Services, VendorService, Address } from 'models';

export async function getBookingsById(id, options = {}) {
  const bookings = await Bookings.findById(id, options.projection, options);
  return bookings;
}

export async function getOne(query, options = {}) {
  const bookings = await Bookings.findOne(query, options.projection, options);
  return bookings;
}

export async function getBookingsList(filter, options = {}) {
  const bookings = await Bookings.find(filter, options.projection, options);
  return bookings;
}

export async function getBookingsListWithPagination(filter, options = {}) {
  const bookings = await Bookings.paginate(filter, options);
  return bookings;
}

export async function createBookings(body, options = {}) {
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  if (body.vendorServiceId) {
    const vendorServiceId = await VendorService.findOne({ _id: body.vendorServiceId });
    if (!vendorServiceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorServiceId is not valid');
    }
  }
  if (body.addressId) {
    const addressId = await Address.findOne({ _id: body.addressId });
    if (!addressId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field addressId is not valid');
    }
  }
  const bookings = await Bookings.create(body);
  return bookings;
}

export async function updateBookings(filter, body, options = {}) {
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  if (body.vendorServiceId) {
    const vendorServiceId = await VendorService.findOne({ _id: body.vendorServiceId });
    if (!vendorServiceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorServiceId is not valid');
    }
  }
  if (body.addressId) {
    const addressId = await Address.findOne({ _id: body.addressId });
    if (!addressId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field addressId is not valid');
    }
  }
  const bookings = await Bookings.findOneAndUpdate(filter, body, options);
  return bookings;
}

export async function updateManyBookings(filter, body, options = {}) {
  const bookings = await Bookings.updateMany(filter, body, options);
  return bookings;
}

export async function removeBookings(filter) {
  const bookings = await Bookings.findOneAndRemove(filter);
  return bookings;
}

export async function removeManyBookings(filter) {
  const bookings = await Bookings.deleteMany(filter);
  return bookings;
}

export async function aggregateBookings(query) {
  const bookings = await Bookings.aggregate(query);
  return bookings;
}

export async function aggregateBookingsWithPagination(query, options = {}) {
  const aggregate = Bookings.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const bookings = await Bookings.aggregatePaginate(aggregate, options);
  return bookings;
}
