/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { BookingTracking, Bookings } from 'models';

export async function getBookingTrackingById(id, options = {}) {
  const bookingTracking = await BookingTracking.findById(id, options.projection, options);
  return bookingTracking;
}

export async function getOne(query, options = {}) {
  const bookingTracking = await BookingTracking.findOne(query, options.projection, options);
  return bookingTracking;
}

export async function getBookingTrackingList(filter, options = {}) {
  const bookingTracking = await BookingTracking.find(filter, options.projection, options);
  return bookingTracking;
}

export async function getBookingTrackingListWithPagination(filter, options = {}) {
  const bookingTracking = await BookingTracking.paginate(filter, options);
  return bookingTracking;
}

export async function createBookingTracking(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  const bookingTracking = await BookingTracking.create(body);
  return bookingTracking;
}

export async function updateBookingTracking(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  const bookingTracking = await BookingTracking.findOneAndUpdate(filter, body, options);
  return bookingTracking;
}

export async function updateManyBookingTracking(filter, body, options = {}) {
  const bookingTracking = await BookingTracking.updateMany(filter, body, options);
  return bookingTracking;
}

export async function removeBookingTracking(filter) {
  const bookingTracking = await BookingTracking.findOneAndRemove(filter);
  return bookingTracking;
}

export async function removeManyBookingTracking(filter) {
  const bookingTracking = await BookingTracking.deleteMany(filter);
  return bookingTracking;
}

export async function aggregateBookingTracking(query) {
  const bookingTracking = await BookingTracking.aggregate(query);
  return bookingTracking;
}

export async function aggregateBookingTrackingWithPagination(query, options = {}) {
  const aggregate = BookingTracking.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const bookingTracking = await BookingTracking.aggregatePaginate(aggregate, options);
  return bookingTracking;
}
