/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Chats, Bookings, User, VendorUser } from 'models';

export async function getChatsById(id, options = {}) {
  const chats = await Chats.findById(id, options.projection, options);
  return chats;
}

export async function getOne(query, options = {}) {
  const chats = await Chats.findOne(query, options.projection, options);
  return chats;
}

export async function getChatsList(filter, options = {}) {
  const chats = await Chats.find(filter, options.projection, options);
  return chats;
}

export async function getChatsListWithPagination(filter, options = {}) {
  const chats = await Chats.paginate(filter, options);
  return chats;
}

export async function createChats(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const chats = await Chats.create(body);
  return chats;
}

export async function updateChats(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const chats = await Chats.findOneAndUpdate(filter, body, options);
  return chats;
}

export async function updateManyChats(filter, body, options = {}) {
  const chats = await Chats.updateMany(filter, body, options);
  return chats;
}

export async function removeChats(filter) {
  const chats = await Chats.findOneAndRemove(filter);
  return chats;
}

export async function removeManyChats(filter) {
  const chats = await Chats.deleteMany(filter);
  return chats;
}

export async function aggregateChats(query) {
  const chats = await Chats.aggregate(query);
  return chats;
}

export async function aggregateChatsWithPagination(query, options = {}) {
  const aggregate = Chats.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const chats = await Chats.aggregatePaginate(aggregate, options);
  return chats;
}
