/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Coupons } from 'models';

export async function getCouponsById(id, options = {}) {
  const coupons = await Coupons.findById(id, options.projection, options);
  return coupons;
}

export async function getOne(query, options = {}) {
  const coupons = await Coupons.findOne(query, options.projection, options);
  return coupons;
}

export async function getCouponsList(filter, options = {}) {
  const coupons = await Coupons.find(filter, options.projection, options);
  return coupons;
}

export async function getCouponsListWithPagination(filter, options = {}) {
  const coupons = await Coupons.paginate(filter, options);
  return coupons;
}

export async function createCoupons(body, options = {}) {
  const coupons = await Coupons.create(body);
  return coupons;
}

export async function updateCoupons(filter, body, options = {}) {
  const coupons = await Coupons.findOneAndUpdate(filter, body, options);
  return coupons;
}

export async function updateManyCoupons(filter, body, options = {}) {
  const coupons = await Coupons.updateMany(filter, body, options);
  return coupons;
}

export async function removeCoupons(filter) {
  const coupons = await Coupons.findOneAndRemove(filter);
  return coupons;
}

export async function removeManyCoupons(filter) {
  const coupons = await Coupons.deleteMany(filter);
  return coupons;
}

export async function aggregateCoupons(query) {
  const coupons = await Coupons.aggregate(query);
  return coupons;
}

export async function aggregateCouponsWithPagination(query, options = {}) {
  const aggregate = Coupons.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const coupons = await Coupons.aggregatePaginate(aggregate, options);
  return coupons;
}
