/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import mongoose from 'mongoose';
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { FavoriteVendor, User, VendorUser, VendorAvailability } from 'models';
import { extractProfilePic } from 'utils/common';

export async function getFavoriteVendorById(id, options = {}) {
  const favoriteVendor = await FavoriteVendor.findById(id, options.projection, options);
  return favoriteVendor;
}

export async function getOne(query, options = {}) {
  const favoriteVendor = await FavoriteVendor.findOne(query, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorList(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.find(filter, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorListWithPagination(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.paginate(filter, options);
  return favoriteVendor;
}

export async function createFavoriteVendor(body = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.create(body);
  return favoriteVendor;
}

export async function updateFavoriteVendor(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.findOneAndUpdate(filter, body, options);
  return favoriteVendor;
}

export async function updateManyFavoriteVendor(filter, body, options = {}) {
  const favoriteVendor = await FavoriteVendor.updateMany(filter, body, options);
  return favoriteVendor;
}

export async function removeFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.findOneAndRemove(filter);
  return favoriteVendor;
}

export async function removeManyFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.deleteMany(filter);
  return favoriteVendor;
}

export async function aggregateFavoriteVendor(query) {
  const favoriteVendor = await FavoriteVendor.aggregate(query);
  return favoriteVendor;
}

export async function aggregateFavoriteVendorWithPagination(query, options = {}) {
  const aggregate = FavoriteVendor.aggregate();
  // eslint-disable-next-line array-callback-return
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const favoriteVendor = await FavoriteVendor.aggregatePaginate(aggregate, options);
  return favoriteVendor;
}

/**
 * Resolve VendorUser model by either VendorUser._id or User._id (vendor account)
 */
export async function resolveVendorUser(vendorIdOrUserId) {
  if (!vendorIdOrUserId) return null;
  const isValid = mongoose.Types.ObjectId.isValid(vendorIdOrUserId);
  if (!isValid) return null;

  const objectId = new mongoose.Types.ObjectId(vendorIdOrUserId);

  // 1. Try finding by VendorUser._id
  let vendor = await VendorUser.findOne({ _id: objectId, isDeleted: { $ne: true } });
  if (vendor) return vendor;

  // 2. Try finding by vendor's userId
  vendor = await VendorUser.findOne({ userId: objectId, isDeleted: { $ne: true } });
  if (vendor) return vendor;

  // 3. Fallback: check if User exists with role 'vendor'
  const user = await User.findOne({ _id: objectId, role: 'vendor', isDeleted: { $ne: true } });
  if (user) {
    vendor = await VendorUser.findOne({ userId: user._id, isDeleted: { $ne: true } });
    if (vendor) return vendor;
  }

  return null;
}

/**
 * Add vendor to customer's favorites
 */
export async function addFavoriteVendor(userId, rawVendorId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!rawVendorId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'vendorId is required');
  }

  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Vendor not found');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const vObjectId = new mongoose.Types.ObjectId(vendorUser._id);

  // Check if favorite record exists (including soft-deleted)
  const existing = await FavoriteVendor.findOne({ userId: uObjectId, vendorId: vObjectId }, null, { withDeleted: true });

  if (existing) {
    if (existing.isDeleted) {
      existing.isDeleted = false;
      existing.deletedAt = undefined;
      existing.deletedBy = undefined;
      existing.updatedBy = uObjectId;
      await existing.save();
    }
    return existing;
  }

  const newFav = await FavoriteVendor.create({
    userId: uObjectId,
    vendorId: vObjectId,
    createdBy: uObjectId,
    updatedBy: uObjectId,
    isDeleted: false,
  });

  return newFav;
}

/**
 * Remove vendor from customer's favorites (by favoriteVendorId or vendorId)
 */
export async function removeCustomerFavoriteVendor(userId, targetId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!targetId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'favoriteVendorId or vendorId is required');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const targetObjectId = mongoose.Types.ObjectId.isValid(targetId) ? new mongoose.Types.ObjectId(targetId) : targetId;

  // 1. Try finding by FavoriteVendor._id
  let fav = await FavoriteVendor.findOne({
    _id: targetObjectId,
    userId: uObjectId,
    isDeleted: { $ne: true },
  });

  // 2. Try finding by VendorUser._id
  if (!fav) {
    fav = await FavoriteVendor.findOne({
      vendorId: targetObjectId,
      userId: uObjectId,
      isDeleted: { $ne: true },
    });
  }

  // 3. Try finding by vendor's userId
  if (!fav) {
    const vu = await VendorUser.findOne({ userId: targetObjectId });
    if (vu) {
      fav = await FavoriteVendor.findOne({
        vendorId: vu._id,
        userId: uObjectId,
        isDeleted: { $ne: true },
      });
    }
  }

  if (!fav) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Favorite vendor record not found or already removed');
  }

  fav.isDeleted = true;
  fav.deletedAt = new Date();
  fav.deletedBy = uObjectId;
  await fav.save();

  return fav;
}

/**
 * Get customer's list of favorite vendors with rich vendor information
 */
export async function getCustomerFavoriteVendorList(userId, options = {}) {
  const page = Math.max(1, parseInt(options.page, 10) || 1);
  const limit = Math.max(1, parseInt(options.limit, 10) || (options.isPaginated ? 10 : 100));
  const skip = (page - 1) * limit;

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const filter = {
    userId: uObjectId,
    isDeleted: { $ne: true },
  };

  const totalDocs = await FavoriteVendor.countDocuments(filter);

  const query = FavoriteVendor.find(filter)
    .sort({ createdAt: -1 })
    .populate({
      path: 'vendorId',
      populate: [
        {
          path: 'userId',
          select: 'name fullName email mobileNumber countryCode profileImage profilePic userProfilePic images location',
        },
        {
          path: 'categoryId',
          select: 'title icon image',
        },
      ],
    });

  if (options.isPaginated) {
    query.skip(skip).limit(limit);
  }

  const rawFavorites = await query.lean();

  const validFavorites = rawFavorites.filter((fav) => fav.vendorId && fav.vendorId.isDeleted !== true);
  const vendorIds = validFavorites.map((fav) => fav.vendorId._id).filter(Boolean);

  const availabilities = await VendorAvailability.find({
    vendorId: { $in: vendorIds },
    isDeleted: { $ne: true },
  }).lean();

  const availMap = new Map();
  availabilities.forEach((va) => {
    if (va.vendorId) {
      availMap.set(va.vendorId.toString(), va);
    }
  });

  const dayNames = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const todayDayName = dayNames[new Date().getDay()];

  const formattedResults = validFavorites.map((fav) => {
    const vu = fav.vendorId;
    const u = vu.userId && typeof vu.userId === 'object' ? vu.userId : {};
    const vIdStr = vu._id.toString();
    const va = availMap.get(vIdStr);

    const isOnline = va && va.isOnline !== undefined ? Boolean(va.isOnline) : true;
    const storeStatus = (va && va.storeStatus) || (isOnline ? 'online' : 'offline');
    const bookingOption = (va && va.bookingOption) || 'instant';
    const instantArrivalEstimate = (va && va.instantArrivalEstimate) || '30-40 mins';

    let isOpenToday = true;
    if (va && va.weeklySchedule && Array.isArray(va.weeklySchedule)) {
      const todaySchedule = va.weeklySchedule.find((s) => s.day && s.day.toLowerCase() === todayDayName);
      if (todaySchedule) {
        isOpenToday = Boolean(todaySchedule.isOpen);
      }
    }

    const isAvailable = isOnline && isOpenToday;
    let statusText = 'Available';
    let statusBadge = 'available';

    if (!isOnline) {
      statusText = 'Currently Unavailable';
      statusBadge = 'offline';
    } else if (!isOpenToday) {
      statusText = 'Closed Today';
      statusBadge = 'closed';
    } else if (bookingOption === 'instant') {
      statusText = `Arriving in ${instantArrivalEstimate}`;
      statusBadge = 'instant';
    } else {
      statusText = 'Open for Schedule';
      statusBadge = 'schedule';
    }

    const vendorPic = extractProfilePic(u) || extractProfilePic(vu) || '';
    const businessName = vu.businessName || u.businessName || u.fullName || u.name || 'Vendor';
    const rating = vu.rating !== undefined && vu.rating !== null ? Number(vu.rating) : 0;
    const totalReviews = vu.totalReviews !== undefined && vu.totalReviews !== null ? Number(vu.totalReviews) : 0;

    const availabilityInfo = {
      isOnline,
      storeStatus,
      isOpenToday,
      isAvailable,
      statusText,
      statusBadge,
      bookingOption,
      instantArrivalEstimate,
      weeklySchedule: (va && va.weeklySchedule) || [],
    };

    return {
      _id: fav._id,
      id: fav._id ? fav._id.toString() : fav.id,
      userId: fav.userId,
      vendorId: vu._id,
      businessName,
      rating,
      averageRating: rating,
      totalReviews,
      profilePic: vendorPic,
      vendorProfilePic: vendorPic,
      profileImage: vendorPic,
      categoryId: vu.categoryId?._id || vu.categoryId,
      categoryTitle: vu.categoryId?.title || '',
      categoryDetails: vu.categoryId || null,
      isFavorite: true,
      vendorAvailability: availabilityInfo,
      vendorUser: {
        ...vu,
        businessName,
        rating,
        averageRating: rating,
        totalReviews,
        profilePic: vendorPic,
        vendorProfilePic: vendorPic,
        profileImage: vendorPic,
        isFavorite: true,
        vendorAvailability: availabilityInfo,
      },
      createdAt: fav.createdAt,
      updatedAt: fav.updatedAt,
    };
  });

  return {
    results: formattedResults,
    docs: formattedResults,
    totalDocs,
    limit,
    page,
    totalPages: Math.ceil(totalDocs / limit),
    hasNextPage: page * limit < totalDocs,
    hasPrevPage: page > 1,
  };
}

/**
 * Toggle customer's favorite vendor status
 */
export async function toggleCustomerFavoriteVendor(userId, rawVendorId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!rawVendorId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'vendorId is required');
  }

  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Vendor not found');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const vObjectId = new mongoose.Types.ObjectId(vendorUser._id);

  const existing = await FavoriteVendor.findOne({
    userId: uObjectId,
    vendorId: vObjectId,
    isDeleted: { $ne: true },
  });

  if (existing) {
    existing.isDeleted = true;
    existing.deletedAt = new Date();
    existing.deletedBy = uObjectId;
    await existing.save();

    return {
      message: 'Vendor removed from favorites successfully',
      isFavorite: false,
      results: existing,
    };
  }

  const fav = await addFavoriteVendor(userId, vendorUser._id);
  return {
    message: 'Vendor added to favorites successfully',
    isFavorite: true,
    results: fav,
  };
}

/**
 * Check if a vendor is favorited by the customer
 */
export async function checkIsVendorFavorite(userId, rawVendorId) {
  if (!userId || !rawVendorId) return false;
  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) return false;

  const existing = await FavoriteVendor.findOne({
    userId: new mongoose.Types.ObjectId(userId),
    vendorId: new mongoose.Types.ObjectId(vendorUser._id),
    isDeleted: { $ne: true },
  });

  return Boolean(existing);
}
