/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import mongoose from 'mongoose';
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { FavoriteVendor, User, VendorUser, VendorAvailability, Address } from 'models';
import { extractProfilePic } from 'utils/common';
import { calculateVisitCharges } from './vendorUser.service';

/**
 * Calculate distance between two coordinates in kilometers using Haversine formula
 */
export function calculateDistanceInKm(lat1, lon1, lat2, lon2) {
  if (
    lat1 === undefined ||
    lat1 === null ||
    lon1 === undefined ||
    lon1 === null ||
    lat2 === undefined ||
    lat2 === null ||
    lon2 === undefined ||
    lon2 === null ||
    Number.isNaN(Number(lat1)) ||
    Number.isNaN(Number(lon1)) ||
    Number.isNaN(Number(lat2)) ||
    Number.isNaN(Number(lon2))
  ) {
    return null;
  }
  const R = 6371; // Earth's radius in km
  const dLat = ((Number(lat2) - Number(lat1)) * Math.PI) / 180;
  const dLon = ((Number(lon2) - Number(lon1)) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((Number(lat1) * Math.PI) / 180) *
      Math.cos((Number(lat2) * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const dist = R * c;
  return Math.round(dist * 100) / 100;
}

/**
 * Compute vendor visiting charges based on service radius tiers and distance in km
 */
export function computeVendorCharges(vendorUser, distanceKm = null) {
  let visitCharges = vendorUser && vendorUser.visitCharges;
  if (!visitCharges || !Array.isArray(visitCharges) || visitCharges.length === 0) {
    const radius = (vendorUser && vendorUser.serviceRadius) || 15;
    visitCharges = calculateVisitCharges(radius);
  }

  let matchedCharge = null;
  if (distanceKm !== null && distanceKm !== undefined && Array.isArray(visitCharges) && visitCharges.length > 0) {
    const matched = visitCharges.find((vc) => distanceKm >= vc.minDistance && distanceKm <= vc.maxDistance);
    if (matched && matched.charge !== undefined && matched.charge !== null) {
      matchedCharge = matched.charge;
    } else {
      const lastTier = visitCharges[visitCharges.length - 1];
      if (lastTier && distanceKm > lastTier.maxDistance) {
        matchedCharge = lastTier.charge;
      }
    }
  }

  if (matchedCharge === null) {
    if (Array.isArray(visitCharges) && visitCharges.length > 0 && visitCharges[0] && visitCharges[0].charge !== undefined) {
      matchedCharge = visitCharges[0].charge;
    } else {
      matchedCharge = 100;
    }
  }

  return {
    charge: matchedCharge,
    visitCharges,
  };
}

export async function getFavoriteVendorById(id, options = {}) {
  const favoriteVendor = await FavoriteVendor.findById(id, options.projection, options);
  return favoriteVendor;
}

export async function getOne(query, options = {}) {
  const favoriteVendor = await FavoriteVendor.findOne(query, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorList(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.find(filter, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorListWithPagination(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.paginate(filter, options);
  return favoriteVendor;
}

export async function createFavoriteVendor(body = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.create(body);
  return favoriteVendor;
}

export async function updateFavoriteVendor(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.findOneAndUpdate(filter, body, options);
  return favoriteVendor;
}

export async function updateManyFavoriteVendor(filter, body, options = {}) {
  const favoriteVendor = await FavoriteVendor.updateMany(filter, body, options);
  return favoriteVendor;
}

export async function removeFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.findOneAndRemove(filter);
  return favoriteVendor;
}

export async function removeManyFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.deleteMany(filter);
  return favoriteVendor;
}

export async function aggregateFavoriteVendor(query) {
  const favoriteVendor = await FavoriteVendor.aggregate(query);
  return favoriteVendor;
}

export async function aggregateFavoriteVendorWithPagination(query, options = {}) {
  const aggregate = FavoriteVendor.aggregate();
  // eslint-disable-next-line array-callback-return
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const favoriteVendor = await FavoriteVendor.aggregatePaginate(aggregate, options);
  return favoriteVendor;
}

/**
 * Resolve VendorUser model by either VendorUser._id or User._id (vendor account)
 */
export async function resolveVendorUser(vendorIdOrUserId) {
  if (!vendorIdOrUserId) return null;
  const isValid = mongoose.Types.ObjectId.isValid(vendorIdOrUserId);
  if (!isValid) return null;

  const objectId = new mongoose.Types.ObjectId(vendorIdOrUserId);

  // 1. Try finding by VendorUser._id
  let vendor = await VendorUser.findOne({ _id: objectId, isDeleted: { $ne: true } });
  if (vendor) return vendor;

  // 2. Try finding by vendor's userId
  vendor = await VendorUser.findOne({ userId: objectId, isDeleted: { $ne: true } });
  if (vendor) return vendor;

  // 3. Fallback: check if User exists with role 'vendor'
  const user = await User.findOne({ _id: objectId, role: 'vendor', isDeleted: { $ne: true } });
  if (user) {
    vendor = await VendorUser.findOne({ userId: user._id, isDeleted: { $ne: true } });
    if (vendor) return vendor;
  }

  return null;
}

/**
 * Add vendor to customer's favorites
 */
export async function addFavoriteVendor(userId, rawVendorId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!rawVendorId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'vendorId is required');
  }

  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Vendor not found');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const vObjectId = new mongoose.Types.ObjectId(vendorUser._id);

  // Check if favorite record exists (including soft-deleted)
  const existing = await FavoriteVendor.findOne({ userId: uObjectId, vendorId: vObjectId }, null, { withDeleted: true });

  if (existing) {
    if (existing.isDeleted) {
      existing.isDeleted = false;
      existing.deletedAt = undefined;
      existing.deletedBy = undefined;
      existing.updatedBy = uObjectId;
      await existing.save();
    }
    return existing;
  }

  const newFav = await FavoriteVendor.create({
    userId: uObjectId,
    vendorId: vObjectId,
    createdBy: uObjectId,
    updatedBy: uObjectId,
    isDeleted: false,
  });

  return newFav;
}

/**
 * Remove vendor from customer's favorites (by favoriteVendorId or vendorId)
 */
export async function removeCustomerFavoriteVendor(userId, targetId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!targetId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'favoriteVendorId or vendorId is required');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const targetObjectId = mongoose.Types.ObjectId.isValid(targetId) ? new mongoose.Types.ObjectId(targetId) : targetId;

  // 1. Try finding by FavoriteVendor._id
  let fav = await FavoriteVendor.findOne({
    _id: targetObjectId,
    userId: uObjectId,
    isDeleted: { $ne: true },
  });

  // 2. Try finding by VendorUser._id
  if (!fav) {
    fav = await FavoriteVendor.findOne({
      vendorId: targetObjectId,
      userId: uObjectId,
      isDeleted: { $ne: true },
    });
  }

  // 3. Try finding by vendor's userId
  if (!fav) {
    const vu = await VendorUser.findOne({ userId: targetObjectId });
    if (vu) {
      fav = await FavoriteVendor.findOne({
        vendorId: vu._id,
        userId: uObjectId,
        isDeleted: { $ne: true },
      });
    }
  }

  if (!fav) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Favorite vendor record not found or already removed');
  }

  fav.isDeleted = true;
  fav.deletedAt = new Date();
  fav.deletedBy = uObjectId;
  await fav.save();

  return fav;
}

/**
 * Get customer's list of favorite vendors with rich vendor information
 */
export async function getCustomerFavoriteVendorList(userId, options = {}, currentUser = null) {
  const page = Math.max(1, parseInt(options.page, 10) || 1);
  const limit = Math.max(1, parseInt(options.limit, 10) || (options.isPaginated ? 10 : 100));
  const skip = (page - 1) * limit;

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const filter = {
    userId: uObjectId,
    isDeleted: { $ne: true },
  };

  // Resolve customer location coordinates
  let customerLat = null;
  let customerLon = null;

  if (
    options.latitude !== undefined &&
    options.latitude !== null &&
    options.longitude !== undefined &&
    options.longitude !== null
  ) {
    const pLat = parseFloat(options.latitude);
    const pLon = parseFloat(options.longitude);
    if (!Number.isNaN(pLat) && !Number.isNaN(pLon)) {
      customerLat = pLat;
      customerLon = pLon;
    }
  }

  if (customerLat === null || customerLon === null) {
    const custUser = currentUser || (await User.findById(uObjectId).select('location latitude longitude').lean());
    if (
      custUser &&
      custUser.location &&
      Array.isArray(custUser.location.coordinates) &&
      custUser.location.coordinates.length === 2
    ) {
      const [lon, lat] = custUser.location.coordinates;
      if (!Number.isNaN(Number(lat)) && !Number.isNaN(Number(lon))) {
        customerLat = Number(lat);
        customerLon = Number(lon);
      }
    } else if (
      custUser &&
      custUser.latitude !== undefined &&
      custUser.latitude !== null &&
      custUser.longitude !== undefined &&
      custUser.longitude !== null
    ) {
      customerLat = Number(custUser.latitude);
      customerLon = Number(custUser.longitude);
    }
  }

  if (customerLat === null || customerLon === null) {
    try {
      const defaultAddr = await Address.findOne({
        userId: uObjectId,
        isDeleted: { $ne: true },
      })
        .sort({ isDefault: -1, updatedAt: -1 })
        .lean();

      if (
        defaultAddr &&
        defaultAddr.location &&
        Array.isArray(defaultAddr.location.coordinates) &&
        defaultAddr.location.coordinates.length === 2
      ) {
        const [lon, lat] = defaultAddr.location.coordinates;
        if (!Number.isNaN(Number(lat)) && !Number.isNaN(Number(lon))) {
          customerLat = Number(lat);
          customerLon = Number(lon);
        }
      } else if (
        defaultAddr &&
        defaultAddr.latitude !== undefined &&
        defaultAddr.latitude !== null &&
        defaultAddr.longitude !== undefined &&
        defaultAddr.longitude !== null
      ) {
        customerLat = Number(defaultAddr.latitude);
        customerLon = Number(defaultAddr.longitude);
      }
    } catch (e) {
      // Ignore address lookup failure
    }
  }

  const totalDocs = await FavoriteVendor.countDocuments(filter);

  const query = FavoriteVendor.find(filter)
    .sort({ createdAt: -1 })
    .populate({
      path: 'vendorId',
      populate: [
        {
          path: 'userId',
          select:
            'name fullName email mobileNumber countryCode profileImage profilePic userProfilePic images location latitude longitude',
        },
        {
          path: 'categoryId',
          select: 'title icon image',
        },
      ],
    });

  if (options.isPaginated) {
    query.skip(skip).limit(limit);
  }

  const rawFavorites = await query.lean();

  const validFavorites = rawFavorites.filter((fav) => fav.vendorId && fav.vendorId.isDeleted !== true);
  const vendorIds = validFavorites.map((fav) => fav.vendorId._id).filter(Boolean);

  const availabilities = await VendorAvailability.find({
    vendorId: { $in: vendorIds },
    isDeleted: { $ne: true },
  }).lean();

  const availMap = new Map();
  availabilities.forEach((va) => {
    if (va.vendorId) {
      availMap.set(va.vendorId.toString(), va);
    }
  });

  const dayNames = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const todayDayName = dayNames[new Date().getDay()];

  const formattedResults = validFavorites.map((fav) => {
    const vu = fav.vendorId;
    const u = vu.userId && typeof vu.userId === 'object' ? vu.userId : {};
    const vIdStr = vu._id.toString();
    const va = availMap.get(vIdStr);

    const isOnline = va && va.isOnline !== undefined ? Boolean(va.isOnline) : true;
    const storeStatus = (va && va.storeStatus) || (isOnline ? 'online' : 'offline');
    const bookingOption = (va && va.bookingOption) || 'instant';
    const instantArrivalEstimate = (va && va.instantArrivalEstimate) || '30-40 mins';

    let isOpenToday = true;
    if (va && va.weeklySchedule && Array.isArray(va.weeklySchedule)) {
      const todaySchedule = va.weeklySchedule.find((s) => s.day && s.day.toLowerCase() === todayDayName);
      if (todaySchedule) {
        isOpenToday = Boolean(todaySchedule.isOpen);
      }
    }

    const isAvailable = isOnline && isOpenToday;
    let statusText = 'Available';
    let statusBadge = 'available';

    if (!isOnline) {
      statusText = 'Currently Unavailable';
      statusBadge = 'offline';
    } else if (!isOpenToday) {
      statusText = 'Closed Today';
      statusBadge = 'closed';
    } else if (bookingOption === 'instant') {
      statusText = `Arriving in ${instantArrivalEstimate}`;
      statusBadge = 'instant';
    } else {
      statusText = 'Open for Schedule';
      statusBadge = 'schedule';
    }

    // Resolve vendor coordinates
    let vendorLat = null;
    let vendorLon = null;

    if (u.location && Array.isArray(u.location.coordinates) && u.location.coordinates.length === 2) {
      [vendorLon, vendorLat] = u.location.coordinates;
    } else if (vu.location && Array.isArray(vu.location.coordinates) && vu.location.coordinates.length === 2) {
      [vendorLon, vendorLat] = vu.location.coordinates;
    } else if (u.latitude !== undefined && u.latitude !== null && u.longitude !== undefined && u.longitude !== null) {
      vendorLat = Number(u.latitude);
      vendorLon = Number(u.longitude);
    } else if (vu.latitude !== undefined && vu.latitude !== null && vu.longitude !== undefined && vu.longitude !== null) {
      vendorLat = Number(vu.latitude);
      vendorLon = Number(vu.longitude);
    }

    const distance = calculateDistanceInKm(customerLat, customerLon, vendorLat, vendorLon);
    const { charge, visitCharges: computedVisitCharges } = computeVendorCharges(vu, distance);

    const vendorPic = extractProfilePic(u) || extractProfilePic(vu) || '';
    const businessName = vu.businessName || u.businessName || u.fullName || u.name || 'Vendor';
    const rating = vu.rating !== undefined && vu.rating !== null ? Number(vu.rating) : 0;
    const totalReviews = vu.totalReviews !== undefined && vu.totalReviews !== null ? Number(vu.totalReviews) : 0;

    const availabilityInfo = {
      isOnline,
      storeStatus,
      isOpenToday,
      isAvailable,
      statusText,
      statusBadge,
      bookingOption,
      instantArrivalEstimate,
      weeklySchedule: (va && va.weeklySchedule) || [],
    };

    return {
      _id: fav._id,
      id: fav._id ? fav._id.toString() : fav.id,
      userId: fav.userId,
      vendorId: vu._id,
      businessName,
      rating,
      averageRating: rating,
      totalReviews,
      profilePic: vendorPic,
      vendorProfilePic: vendorPic,
      profileImage: vendorPic,
      categoryId: vu.categoryId?._id || vu.categoryId,
      categoryTitle: vu.categoryId?.title || '',
      categoryDetails: vu.categoryId || null,
      isFavorite: true,
      distance,
      charges: charge,
      charge,
      visitCharge: charge,
      visitCharges: computedVisitCharges,
      vendorAvailability: availabilityInfo,
      vendorUser: {
        ...vu,
        businessName,
        rating,
        averageRating: rating,
        totalReviews,
        profilePic: vendorPic,
        vendorProfilePic: vendorPic,
        profileImage: vendorPic,
        isFavorite: true,
        distance,
        charges: charge,
        charge,
        visitCharge: charge,
        visitCharges: computedVisitCharges,
        vendorAvailability: availabilityInfo,
      },
      createdAt: fav.createdAt,
      updatedAt: fav.updatedAt,
    };
  });

  return {
    results: formattedResults,
    docs: formattedResults,
    totalDocs,
    limit,
    page,
    totalPages: Math.ceil(totalDocs / limit),
    hasNextPage: page * limit < totalDocs,
    hasPrevPage: page > 1,
  };
}

/**
 * Toggle customer's favorite vendor status
 */
export async function toggleCustomerFavoriteVendor(userId, rawVendorId) {
  if (!userId) {
    throw new ApiError(httpStatus.UNAUTHORIZED, 'User authentication required');
  }
  if (!rawVendorId) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'vendorId is required');
  }

  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Vendor not found');
  }

  const uObjectId = new mongoose.Types.ObjectId(userId);
  const vObjectId = new mongoose.Types.ObjectId(vendorUser._id);

  const existing = await FavoriteVendor.findOne({
    userId: uObjectId,
    vendorId: vObjectId,
    isDeleted: { $ne: true },
  });

  if (existing) {
    existing.isDeleted = true;
    existing.deletedAt = new Date();
    existing.deletedBy = uObjectId;
    await existing.save();

    return {
      message: 'Vendor removed from favorites successfully',
      isFavorite: false,
      results: existing,
    };
  }

  const fav = await addFavoriteVendor(userId, vendorUser._id);
  return {
    message: 'Vendor added to favorites successfully',
    isFavorite: true,
    results: fav,
  };
}

/**
 * Check if a vendor is favorited by the customer
 */
export async function checkIsVendorFavorite(userId, rawVendorId) {
  if (!userId || !rawVendorId) return false;
  const vendorUser = await resolveVendorUser(rawVendorId);
  if (!vendorUser) return false;

  const existing = await FavoriteVendor.findOne({
    userId: new mongoose.Types.ObjectId(userId),
    vendorId: new mongoose.Types.ObjectId(vendorUser._id),
    isDeleted: { $ne: true },
  });

  return Boolean(existing);
}
