/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { FavoriteVendor, User, VendorUser } from 'models';

export async function getFavoriteVendorById(id, options = {}) {
  const favoriteVendor = await FavoriteVendor.findById(id, options.projection, options);
  return favoriteVendor;
}

export async function getOne(query, options = {}) {
  const favoriteVendor = await FavoriteVendor.findOne(query, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorList(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.find(filter, options.projection, options);
  return favoriteVendor;
}

export async function getFavoriteVendorListWithPagination(filter, options = {}) {
  const favoriteVendor = await FavoriteVendor.paginate(filter, options);
  return favoriteVendor;
}

export async function createFavoriteVendor(body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.create(body);
  return favoriteVendor;
}

export async function updateFavoriteVendor(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const favoriteVendor = await FavoriteVendor.findOneAndUpdate(filter, body, options);
  return favoriteVendor;
}

export async function updateManyFavoriteVendor(filter, body, options = {}) {
  const favoriteVendor = await FavoriteVendor.updateMany(filter, body, options);
  return favoriteVendor;
}

export async function removeFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.findOneAndRemove(filter);
  return favoriteVendor;
}

export async function removeManyFavoriteVendor(filter) {
  const favoriteVendor = await FavoriteVendor.deleteMany(filter);
  return favoriteVendor;
}

export async function aggregateFavoriteVendor(query) {
  const favoriteVendor = await FavoriteVendor.aggregate(query);
  return favoriteVendor;
}

export async function aggregateFavoriteVendorWithPagination(query, options = {}) {
  const aggregate = FavoriteVendor.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const favoriteVendor = await FavoriteVendor.aggregatePaginate(aggregate, options);
  return favoriteVendor;
}
