/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Messages, Chats } from 'models';

export async function getMessagesById(id, options = {}) {
  const messages = await Messages.findById(id, options.projection, options);
  return messages;
}

export async function getOne(query, options = {}) {
  const messages = await Messages.findOne(query, options.projection, options);
  return messages;
}

export async function getMessagesList(filter, options = {}) {
  const messages = await Messages.find(filter, options.projection, options);
  return messages;
}

export async function getMessagesListWithPagination(filter, options = {}) {
  const messages = await Messages.paginate(filter, options);
  return messages;
}

export async function createMessages(body, options = {}) {
  if (body.chatId) {
    const chatId = await Chats.findOne({ _id: body.chatId });
    if (!chatId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field chatId is not valid');
    }
  }
  const messages = await Messages.create(body);
  return messages;
}

export async function updateMessages(filter, body, options = {}) {
  if (body.chatId) {
    const chatId = await Chats.findOne({ _id: body.chatId });
    if (!chatId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field chatId is not valid');
    }
  }
  const messages = await Messages.findOneAndUpdate(filter, body, options);
  return messages;
}

export async function updateManyMessages(filter, body, options = {}) {
  const messages = await Messages.updateMany(filter, body, options);
  return messages;
}

export async function removeMessages(filter) {
  const messages = await Messages.findOneAndRemove(filter);
  return messages;
}

export async function removeManyMessages(filter) {
  const messages = await Messages.deleteMany(filter);
  return messages;
}

export async function aggregateMessages(query) {
  const messages = await Messages.aggregate(query);
  return messages;
}

export async function aggregateMessagesWithPagination(query, options = {}) {
  const aggregate = Messages.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const messages = await Messages.aggregatePaginate(aggregate, options);
  return messages;
}
