/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Notifications } from 'models';

export async function getNotificationsById(id, options = {}) {
  const notifications = await Notifications.findById(id, options.projection, options);
  return notifications;
}

export async function getOne(query, options = {}) {
  const notifications = await Notifications.findOne(query, options.projection, options);
  return notifications;
}

export async function getNotificationsList(filter, options = {}) {
  const notifications = await Notifications.find(filter, options.projection, options);
  return notifications;
}

export async function getNotificationsListWithPagination(filter, options = {}) {
  const notifications = await Notifications.paginate(filter, options);
  return notifications;
}

export async function createNotifications(body, options = {}) {
  const notifications = await Notifications.create(body);
  return notifications;
}

export async function updateNotifications(filter, body, options = {}) {
  const notifications = await Notifications.findOneAndUpdate(filter, body, options);
  return notifications;
}

export async function updateManyNotifications(filter, body, options = {}) {
  const notifications = await Notifications.updateMany(filter, body, options);
  return notifications;
}

export async function removeNotifications(filter) {
  const notifications = await Notifications.findOneAndRemove(filter);
  return notifications;
}

export async function removeManyNotifications(filter) {
  const notifications = await Notifications.deleteMany(filter);
  return notifications;
}

export async function aggregateNotifications(query) {
  const notifications = await Notifications.aggregate(query);
  return notifications;
}

export async function aggregateNotificationsWithPagination(query, options = {}) {
  const aggregate = Notifications.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const notifications = await Notifications.aggregatePaginate(aggregate, options);
  return notifications;
}
