/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Payments, Bookings, User, VendorUser } from 'models';

export async function getPaymentsById(id, options = {}) {
  const payments = await Payments.findById(id, options.projection, options);
  return payments;
}

export async function getOne(query, options = {}) {
  const payments = await Payments.findOne(query, options.projection, options);
  return payments;
}

export async function getPaymentsList(filter, options = {}) {
  const payments = await Payments.find(filter, options.projection, options);
  return payments;
}

export async function getPaymentsListWithPagination(filter, options = {}) {
  const payments = await Payments.paginate(filter, options);
  return payments;
}

export async function createPayments(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const payments = await Payments.create(body);
  return payments;
}

export async function updatePayments(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const payments = await Payments.findOneAndUpdate(filter, body, options);
  return payments;
}

export async function updateManyPayments(filter, body, options = {}) {
  const payments = await Payments.updateMany(filter, body, options);
  return payments;
}

export async function removePayments(filter) {
  const payments = await Payments.findOneAndRemove(filter);
  return payments;
}

export async function removeManyPayments(filter) {
  const payments = await Payments.deleteMany(filter);
  return payments;
}

export async function aggregatePayments(query) {
  const payments = await Payments.aggregate(query);
  return payments;
}

export async function aggregatePaymentsWithPagination(query, options = {}) {
  const aggregate = Payments.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const payments = await Payments.aggregatePaginate(aggregate, options);
  return payments;
}
