/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Payouts, VendorUser, Wallet } from 'models';

export async function getPayoutsById(id, options = {}) {
  const payouts = await Payouts.findById(id, options.projection, options);
  return payouts;
}

export async function getOne(query, options = {}) {
  const payouts = await Payouts.findOne(query, options.projection, options);
  return payouts;
}

export async function getPayoutsList(filter, options = {}) {
  const payouts = await Payouts.find(filter, options.projection, options);
  return payouts;
}

export async function getPayoutsListWithPagination(filter, options = {}) {
  const payouts = await Payouts.paginate(filter, options);
  return payouts;
}

export async function createPayouts(body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.walletId) {
    const walletId = await Wallet.findOne({ _id: body.walletId });
    if (!walletId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field walletId is not valid');
    }
  }
  const payouts = await Payouts.create(body);
  return payouts;
}

export async function updatePayouts(filter, body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.walletId) {
    const walletId = await Wallet.findOne({ _id: body.walletId });
    if (!walletId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field walletId is not valid');
    }
  }
  const payouts = await Payouts.findOneAndUpdate(filter, body, options);
  return payouts;
}

export async function updateManyPayouts(filter, body, options = {}) {
  const payouts = await Payouts.updateMany(filter, body, options);
  return payouts;
}

export async function removePayouts(filter) {
  const payouts = await Payouts.findOneAndRemove(filter);
  return payouts;
}

export async function removeManyPayouts(filter) {
  const payouts = await Payouts.deleteMany(filter);
  return payouts;
}

export async function aggregatePayouts(query) {
  const payouts = await Payouts.aggregate(query);
  return payouts;
}

export async function aggregatePayoutsWithPagination(query, options = {}) {
  const aggregate = Payouts.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const payouts = await Payouts.aggregatePaginate(aggregate, options);
  return payouts;
}
