/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Reviews, Bookings, User, VendorUser } from 'models';

export async function getReviewsById(id, options = {}) {
  const reviews = await Reviews.findById(id, options.projection, options);
  return reviews;
}

export async function getOne(query, options = {}) {
  const reviews = await Reviews.findOne(query, options.projection, options);
  return reviews;
}

export async function getReviewsList(filter, options = {}) {
  const reviews = await Reviews.find(filter, options.projection, options);
  return reviews;
}

export async function getReviewsListWithPagination(filter, options = {}) {
  const reviews = await Reviews.paginate(filter, options);
  return reviews;
}

export async function createReviews(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const reviews = await Reviews.create(body);
  return reviews;
}

export async function updateReviews(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  if (body.customerId) {
    const customerId = await User.findOne({ _id: body.customerId });
    if (!customerId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field customerId is not valid');
    }
  }
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const reviews = await Reviews.findOneAndUpdate(filter, body, options);
  return reviews;
}

export async function updateManyReviews(filter, body, options = {}) {
  const reviews = await Reviews.updateMany(filter, body, options);
  return reviews;
}

export async function removeReviews(filter) {
  const reviews = await Reviews.findOneAndRemove(filter);
  return reviews;
}

export async function removeManyReviews(filter) {
  const reviews = await Reviews.deleteMany(filter);
  return reviews;
}

export async function aggregateReviews(query) {
  const reviews = await Reviews.aggregate(query);
  return reviews;
}

export async function aggregateReviewsWithPagination(query, options = {}) {
  const aggregate = Reviews.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const reviews = await Reviews.aggregatePaginate(aggregate, options);
  return reviews;
}
