/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Services, User } from 'models';

export async function getServicesById(id, options = {}) {
  const services = await Services.findById(id, options.projection, options);
  return services;
}

export async function getOne(query, options = {}) {
  const services = await Services.findOne(query, options.projection, options);
  return services;
}

export async function getServicesList(filter, options = {}) {
  const services = await Services.find(filter, options.projection, options);
  return services;
}

export async function getServicesListWithPagination(filter, options = {}) {
  const services = await Services.paginate(filter, options);
  return services;
}

export async function createServices(body, options = {}) {
  const services = await Services.create(body);
  return services;
}

export async function createManyServices(bodies) {
  const services = await Services.insertMany(bodies);
  return services;
}

export async function updateServices(filter, body, options = {}) {
  const services = await Services.findOneAndUpdate(filter, body, options);
  return services;
}

export async function updateManyServices(filter, body, options = {}) {
  const services = await Services.updateMany(filter, body, options);
  return services;
}

export async function removeServices(filter) {
  const services = await Services.findOneAndRemove(filter);
  return services;
}

export async function removeManyServices(filter) {
  const services = await Services.deleteMany(filter);
  return services;
}

export async function aggregateServices(query) {
  const services = await Services.aggregate(query);
  return services;
}

export async function aggregateServicesWithPagination(query, options = {}) {
  const aggregate = Services.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const services = await Services.aggregatePaginate(aggregate, options);
  return services;
}

export async function getNearServices(longitude, latitude, filter = {}, options = {}) {
  const { page = 1, limit = 10 } = options;
  const skip = (page - 1) * limit;

  const matchStage = {
    role: 'vendor',
    isDeleted: { $ne: true },
  };

  const serviceMatch = {
    'serviceDetails.isDeleted': { $ne: true },
    'serviceDetails.isActive': true,
  };

  if (filter.categoryId) {
    serviceMatch['serviceDetails.categoryId'] = filter.categoryId;
  }

  const pipeline = [
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [parseFloat(longitude), parseFloat(latitude)],
        },
        distanceField: 'distance',
        spherical: true,
        query: matchStage,
      },
    },
    {
      $lookup: {
        from: 'VendorService',
        localField: '_id',
        foreignField: 'vendorId',
        as: 'vendorServices',
      },
    },
    { $unwind: '$vendorServices' },
    {
      $lookup: {
        from: 'Services',
        localField: 'vendorServices.serviceId',
        foreignField: '_id',
        as: 'serviceDetails',
      },
    },
    { $unwind: '$serviceDetails' },
    { $match: serviceMatch },
    {
      $addFields: {
        isWithin5km: {
          $cond: { if: { $lte: ['$distance', 5000] }, then: 1, else: 0 },
        },
      },
    },
    {
      $group: {
        _id: '$serviceDetails._id',
        title: { $first: '$serviceDetails.title' },
        description: { $first: '$serviceDetails.description' },
        categoryId: { $first: '$serviceDetails.categoryId' },
        isActive: { $first: '$serviceDetails.isActive' },
        nearestDistance: { $min: '$distance' },
        isWithin5km: { $max: '$isWithin5km' },
      },
    },
    {
      $sort: {
        isWithin5km: -1,
        nearestDistance: 1,
      },
    },
    {
      $facet: {
        metadata: [{ $count: 'total' }],
        data: [{ $skip: skip }, { $limit: limit }],
      },
    },
  ];

  const results = await User.aggregate(pipeline);
  const total = results[0]?.metadata[0]?.total || 0;
  const data = results[0]?.data || [];

  return {
    docs: data,
    totalDocs: total,
    limit,
    page,
    totalPages: Math.ceil(total / limit),
  };
}
