/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Services } from 'models';

export async function getServicesById(id, options = {}) {
  const services = await Services.findById(id, options.projection, options);
  return services;
}

export async function getOne(query, options = {}) {
  const services = await Services.findOne(query, options.projection, options);
  return services;
}

export async function getServicesList(filter, options = {}) {
  const services = await Services.find(filter, options.projection, options);
  return services;
}

export async function getServicesListWithPagination(filter, options = {}) {
  const services = await Services.paginate(filter, options);
  return services;
}

export async function createServices(body, options = {}) {
  const services = await Services.create(body);
  return services;
}

export async function updateServices(filter, body, options = {}) {
  const services = await Services.findOneAndUpdate(filter, body, options);
  return services;
}

export async function updateManyServices(filter, body, options = {}) {
  const services = await Services.updateMany(filter, body, options);
  return services;
}

export async function removeServices(filter) {
  const services = await Services.findOneAndRemove(filter);
  return services;
}

export async function removeManyServices(filter) {
  const services = await Services.deleteMany(filter);
  return services;
}

export async function aggregateServices(query) {
  const services = await Services.aggregate(query);
  return services;
}

export async function aggregateServicesWithPagination(query, options = {}) {
  const aggregate = Services.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const services = await Services.aggregatePaginate(aggregate, options);
  return services;
}
