/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { SupportTicket, Bookings } from 'models';

export async function getSupportTicketById(id, options = {}) {
  const supportTicket = await SupportTicket.findById(id, options.projection, options);
  return supportTicket;
}

export async function getOne(query, options = {}) {
  const supportTicket = await SupportTicket.findOne(query, options.projection, options);
  return supportTicket;
}

export async function getSupportTicketList(filter, options = {}) {
  const supportTicket = await SupportTicket.find(filter, options.projection, options);
  return supportTicket;
}

export async function getSupportTicketListWithPagination(filter, options = {}) {
  const supportTicket = await SupportTicket.paginate(filter, options);
  return supportTicket;
}

export async function createSupportTicket(body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  const supportTicket = await SupportTicket.create(body);
  return supportTicket;
}

export async function updateSupportTicket(filter, body, options = {}) {
  if (body.bookingId) {
    const bookingId = await Bookings.findOne({ _id: body.bookingId });
    if (!bookingId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bookingId is not valid');
    }
  }
  const supportTicket = await SupportTicket.findOneAndUpdate(filter, body, options);
  return supportTicket;
}

export async function updateManySupportTicket(filter, body, options = {}) {
  const supportTicket = await SupportTicket.updateMany(filter, body, options);
  return supportTicket;
}

export async function removeSupportTicket(filter) {
  const supportTicket = await SupportTicket.findOneAndRemove(filter);
  return supportTicket;
}

export async function removeManySupportTicket(filter) {
  const supportTicket = await SupportTicket.deleteMany(filter);
  return supportTicket;
}

export async function aggregateSupportTicket(query) {
  const supportTicket = await SupportTicket.aggregate(query);
  return supportTicket;
}

export async function aggregateSupportTicketWithPagination(query, options = {}) {
  const aggregate = SupportTicket.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const supportTicket = await SupportTicket.aggregatePaginate(aggregate, options);
  return supportTicket;
}
