/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { VendorAvailability } from 'models';

export async function getVendorAvailabilityById(id, options = {}) {
  const vendorAvailability = await VendorAvailability.findById(id, options.projection, options);
  return vendorAvailability;
}

export async function getOne(query, options = {}) {
  const vendorAvailability = await VendorAvailability.findOne(query, options.projection, options);
  return vendorAvailability;
}

export async function getVendorAvailabilityList(filter, options = {}) {
  const vendorAvailability = await VendorAvailability.find(filter, options.projection, options);
  return vendorAvailability;
}

export async function getVendorAvailabilityListWithPagination(filter, options = {}) {
  const vendorAvailability = await VendorAvailability.paginate(filter, options);
  return vendorAvailability;
}

export async function createVendorAvailability(body, options = {}) {
  const vendorAvailability = await VendorAvailability.create(body);
  return vendorAvailability;
}

export async function updateVendorAvailability(filter, body, options = {}) {
  const vendorAvailability = await VendorAvailability.findOneAndUpdate(filter, body, options);
  return vendorAvailability;
}

export async function updateManyVendorAvailability(filter, body, options = {}) {
  const vendorAvailability = await VendorAvailability.updateMany(filter, body, options);
  return vendorAvailability;
}

export async function removeVendorAvailability(filter) {
  const vendorAvailability = await VendorAvailability.findOneAndRemove(filter);
  return vendorAvailability;
}

export async function removeManyVendorAvailability(filter) {
  const vendorAvailability = await VendorAvailability.deleteMany(filter);
  return vendorAvailability;
}

export async function aggregateVendorAvailability(query) {
  const vendorAvailability = await VendorAvailability.aggregate(query);
  return vendorAvailability;
}

export async function aggregateVendorAvailabilityWithPagination(query, options = {}) {
  const aggregate = VendorAvailability.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const vendorAvailability = await VendorAvailability.aggregatePaginate(aggregate, options);
  return vendorAvailability;
}
