/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import mongoose from 'mongoose';
import { VendorUser, User, Bank, Categories, VendorService, BusinessAddress, VendorAvailability } from 'models';
import { generateOtp } from 'utils/common';
import { countryCodeService, emailService } from 'services';
import { EnumCodeTypeOfCode } from 'models/enum.model';
import { sendOtpToMobile } from './mobileotp.service';

export async function getVendorUserById(id, options = {}) {
  const vendorUser = await VendorUser.findById(id, options.projection, options).populate('categoryId');
  return vendorUser;
}

export async function getOne(query, options = {}) {
  const vendorUser = await VendorUser.findOne(query, options.projection, options).populate('categoryId');
  return vendorUser;
}

export async function getVendorUserList(filter, options = {}) {
  const vendorUser = await VendorUser.find(filter, options.projection, options).populate('categoryId');
  return vendorUser;
}

export async function getVendorUserListWithPagination(filter, options = {}) {
  const paginateOptions = {
    ...options,
    populate: options.populate ? [].concat(options.populate, 'categoryId') : 'categoryId',
  };
  const vendorUser = await VendorUser.paginate(filter, paginateOptions);
  return vendorUser;
}

export function calculateVisitCharges(serviceRadius) {
  if (!serviceRadius || serviceRadius <= 0) return [];
  const charges = [];

  const tiers = [
    { min: 0, max: 5, charge: 100 },
    { min: 5, max: 10, charge: 150 },
    { min: 10, max: 15, charge: 200 },
    { min: 15, max: 20, charge: 500 },
    { min: 20, max: 25, charge: 700 },
    { min: 25, max: Infinity, charge: 1000 },
  ];

  // eslint-disable-next-line no-restricted-syntax
  for (const tier of tiers) {
    if (serviceRadius > tier.min) {
      const maxDistance = Math.min(serviceRadius, tier.max);
      charges.push({
        minDistance: tier.min,
        maxDistance: maxDistance === Infinity ? serviceRadius : maxDistance,
        charge: tier.charge,
      });
    }
    if (serviceRadius <= tier.max) {
      break;
    }
  }
  return charges;
}

export async function createVendorUser(body = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.bankDetailsId) {
    const bankDetailsId = await Bank.findOne({ _id: body.bankDetailsId });
    if (!bankDetailsId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bankDetailsId is not valid');
    }
  }
  if (body.categoryId) {
    const categoryId = await Categories.findOne({ _id: body.categoryId });
    if (!categoryId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field categoryId is not valid');
    }
  }
  if (body.serviceRadius !== undefined) {
    // eslint-disable-next-line no-param-reassign
    body.visitCharges = calculateVisitCharges(body.serviceRadius);
  }
  const vendorUser = await VendorUser.create(body);
  return vendorUser;
}

export async function updateVendorUser(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.bankDetailsId) {
    const bankDetailsId = await Bank.findOne({ _id: body.bankDetailsId });
    if (!bankDetailsId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bankDetailsId is not valid');
    }
  }
  if (body.categoryId) {
    const categoryId = await Categories.findOne({ _id: body.categoryId });
    if (!categoryId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field categoryId is not valid');
    }
  }
  if (body.serviceRadius !== undefined) {
    // eslint-disable-next-line no-param-reassign
    body.visitCharges = calculateVisitCharges(body.serviceRadius);
  }
  const vendorUser = await VendorUser.findOneAndUpdate(filter, body, options);
  return vendorUser;
}

export async function updateManyVendorUser(filter, body, options = {}) {
  const vendorUser = await VendorUser.updateMany(filter, body, options);
  return vendorUser;
}

export async function removeVendorUser(filter) {
  const vendorUser = await VendorUser.findOneAndRemove(filter);
  return vendorUser;
}

export async function removeManyVendorUser(filter) {
  const vendorUser = await VendorUser.deleteMany(filter);
  return vendorUser;
}

export async function aggregateVendorUser(query) {
  const vendorUser = await VendorUser.aggregate(query);
  return vendorUser;
}

// export async function aggregateVendorUserWithPagination(query, options = {}) {
//   const aggregate = VendorUser.aggregate();
//   query.map((obj) => {
//     aggregate._pipeline.push(obj);
//   });
//   const vendorUser = await VendorUser.aggregatePaginate(aggregate, options);
//   return vendorUser;
// }

export async function updateVendorProfile(user, body) {
  const { name, email, mobileNumber, countryCodeId, profileImage, businessName, gstNumber, categoryId, serviceRadius } =
    body;

  // 1. Update VendorUser details
  const vendorUserUpdate = {};
  if (businessName !== undefined) vendorUserUpdate.businessName = businessName;
  if (gstNumber !== undefined) vendorUserUpdate.gstNumber = gstNumber;
  if (serviceRadius !== undefined) {
    vendorUserUpdate.serviceRadius = serviceRadius;
    vendorUserUpdate.visitCharges = calculateVisitCharges(serviceRadius);
  }
  if (categoryId !== undefined) {
    if (categoryId) {
      const categoryExists = await Categories.findOne({ _id: categoryId });
      if (!categoryExists) {
        throw new ApiError(httpStatus.BAD_REQUEST, 'field categoryId is not valid');
      }
    }
    vendorUserUpdate.categoryId = categoryId || null;
  }

  const updatedVendorUser = await VendorUser.findOneAndUpdate(
    { userId: user._id },
    { $set: vendorUserUpdate, userId: user._id },
    { new: true, upsert: true }
  );

  // 2. Update normal User fields
  const userUpdate = {};
  if (name !== undefined) {
    userUpdate.name = name;
    userUpdate.fullName = name;
  }
  if (profileImage !== undefined) userUpdate.profileImage = profileImage;
  if (businessName !== undefined) userUpdate.businessName = businessName;

  if (Object.keys(userUpdate).length) {
    Object.assign(user, userUpdate);
    await user.save();
  }

  // 3. Handle Email Update Verification
  if (email && email !== user.email) {
    const exists = await User.findOne({
      email,
      _id: { $ne: user._id },
    });

    if (exists) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'Email already taken');
    }

    const otp = generateOtp();
    user.codes.push({
      code: String(otp),
      codeType: EnumCodeTypeOfCode.EMAIL,
      expirationDate: new Date(Date.now() + 10 * 60 * 1000),
      used: false,
    });
    // eslint-disable-next-line no-param-reassign
    user.pendingEmail = email;
    await user.save();

    await emailService.sendOtpVerificationEmail({ email }, otp);

    return {
      user,
      vendorUser: updatedVendorUser,
      verifyRequired: true,
      verifyType: 'email',
      message: 'OTP sent to email. Please verify.',
    };
  }

  // 4. Handle Mobile Update Verification
  if (mobileNumber && mobileNumber !== user.mobileNumber) {
    const country = await countryCodeService.getCountryCodeById(countryCodeId);
    if (!country) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'Valid countryCodeId required');
    }

    const exists = await User.findOne({
      mobileNumber,
      _id: { $ne: user._id },
    });
    if (exists) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'Mobile number already taken');
    }

    const otp = generateOtp();
    user.codes.push({
      code: String(otp),
      codeType: EnumCodeTypeOfCode.MOBILE,
      expirationDate: new Date(Date.now() + 10 * 60 * 1000),
      used: false,
    });
    // eslint-disable-next-line no-param-reassign
    user.pendingMobileNumber = mobileNumber;
    // eslint-disable-next-line no-param-reassign
    user.pendingCountryCode = country.code;
    await user.save();

    await sendOtpToMobile(`${country.code}${mobileNumber}`, otp);

    return {
      user,
      vendorUser: updatedVendorUser,
      verifyRequired: true,
      verifyType: 'mobile',
      message: 'OTP sent to mobile. Please verify.',
    };
  }

  return {
    user,
    vendorUser: updatedVendorUser,
    verifyRequired: false,
    message: 'Profile updated successfully',
  };
}

export async function getNearVendorUsersByCategory(longitude, latitude, categoryId, options = {}) {
  const { page = 1, limit = 10 } = options;
  const skip = (page - 1) * limit;

  const matchStage = {
    role: 'vendor',
    isDeleted: { $ne: true },
  };

  const pipeline = [
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [parseFloat(longitude), parseFloat(latitude)],
        },
        distanceField: 'distance',
        maxDistance: 15000, // 15km limit
        spherical: true,
        query: matchStage,
      },
    },
    {
      $lookup: {
        from: 'VendorUser',
        localField: '_id',
        foreignField: 'userId',
        as: 'vendorUser',
      },
    },
    { $unwind: '$vendorUser' },
    {
      $match: {
        'vendorUser.categoryId': new mongoose.Types.ObjectId(categoryId),
        'vendorUser.isDeleted': { $ne: true },
      },
    },
    {
      $lookup: {
        from: 'Categories',
        localField: 'vendorUser.categoryId',
        foreignField: '_id',
        as: 'categoryDetails',
      },
    },
    { $unwind: { path: '$categoryDetails', preserveNullAndEmptyArrays: true } },
    {
      $lookup: {
        from: 'VendorAvailability',
        localField: 'vendorUser._id',
        foreignField: 'vendorId',
        as: 'vendorAvailability',
      },
    },
    { $unwind: { path: '$vendorAvailability', preserveNullAndEmptyArrays: true } },
    {
      $project: {
        _id: '$vendorUser._id',
        userId: {
          _id: '$_id',
          name: '$name',
          email: '$email',
          mobileNumber: '$mobileNumber',
          countryCode: '$countryCode',
          fullName: '$fullName',
          profileImage: '$profileImage',
          profilePic: '$profilePic',
          location: '$location',
        },
        businessName: { $ifNull: ['$vendorUser.businessName', '$businessName'] },
        gstNumber: '$vendorUser.gstNumber',
        description: '$vendorUser.description',
        experience: '$vendorUser.experience',
        rating: '$vendorUser.rating',
        totalReviews: '$vendorUser.totalReviews',
        serviceRadius: '$vendorUser.serviceRadius',
        visitCharges: '$vendorUser.visitCharges',
        isKycVerified: '$vendorUser.isKycVerified',
        kycStatus: '$vendorUser.kycStatus',
        profileCompleted: '$vendorUser.profileCompleted',
        avgResponseTime: '$vendorUser.avgResponseTime',
        completedBookings: '$vendorUser.completedBookings',
        categoryId: '$vendorUser.categoryId',
        categoryDetails: {
          _id: '$categoryDetails._id',
          title: '$categoryDetails.title',
          icon: '$categoryDetails.icon',
          image: '$categoryDetails.image',
        },
        vendorAvailability: '$vendorAvailability',
        distance: '$distance',
      },
    },
    {
      $sort: {
        distance: 1,
      },
    },
    {
      $facet: {
        metadata: [{ $count: 'total' }],
        data: [{ $skip: skip }, { $limit: limit }],
      },
    },
  ];

  const results = await User.aggregate(pipeline);
  const total = (results[0] && results[0].metadata && results[0].metadata[0] && results[0].metadata[0].total) || 0;
  const data = (results[0] && results[0].data) || [];

  const dayNames = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const todayDayName = dayNames[new Date().getDay()];

  const docsWithCharge = data.map((doc) => {
    let charge = null;
    if (doc.distance !== undefined && doc.distance !== null && doc.visitCharges && Array.isArray(doc.visitCharges)) {
      const distanceKm = doc.distance / 1000;
      const matchedCharge = doc.visitCharges.find((vc) => distanceKm >= vc.minDistance && distanceKm <= vc.maxDistance);
      if (matchedCharge) {
        charge = matchedCharge.charge;
      }
    }

    const va = doc.vendorAvailability;
    const isOnline = va && va.isOnline !== undefined ? Boolean(va.isOnline) : true;
    const storeStatus = (va && va.storeStatus) || (isOnline ? 'online' : 'offline');
    const bookingOption = (va && va.bookingOption) || 'instant';
    const instantArrivalEstimate = (va && va.instantArrivalEstimate) || '30-40 mins';

    // Check if open today in weekly schedule
    let isOpenToday = true;
    if (va && va.weeklySchedule && Array.isArray(va.weeklySchedule)) {
      const todaySchedule = va.weeklySchedule.find((s) => s.day && s.day.toLowerCase() === todayDayName);
      if (todaySchedule) {
        isOpenToday = Boolean(todaySchedule.isOpen);
      }
    }

    const isAvailable = isOnline && isOpenToday;

    let statusText = 'Available';
    let statusBadge = 'available';

    if (!isOnline) {
      statusText = 'Currently Unavailable';
      statusBadge = 'offline';
    } else if (!isOpenToday) {
      statusText = 'Closed Today';
      statusBadge = 'closed';
    } else if (bookingOption === 'instant') {
      statusText = `Arriving in ${instantArrivalEstimate}`;
      statusBadge = 'instant';
    } else {
      statusText = 'Open for Schedule';
      statusBadge = 'schedule';
    }

    const userIdVal = (doc.userId && doc.userId._id) || doc.userId;
    const profilePicVal = (doc.userId && (doc.userId.profilePic || doc.userId.profileImage)) || null;
    const categoryTitleVal = (doc.categoryDetails && doc.categoryDetails.title) || null;

    return {
      _id: doc._id,
      userId: userIdVal,
      categoryId: doc.categoryId,
      businessName: doc.businessName,
      categoryTitle: categoryTitleVal,
      profilePic: profilePicVal,
      charge,
      distance: doc.distance !== undefined && doc.distance !== null ? Math.round((doc.distance / 1000) * 100) / 100 : null,
      vendorAvailability: {
        isOnline,
        storeStatus,
        isOpenToday,
        isAvailable,
        statusText,
        statusBadge,
        bookingOption,
        instantArrivalEstimate,
      },
    };
  });

  return {
    docs: docsWithCharge,
    totalDocs: total,
    limit,
    page,
    totalPages: Math.ceil(total / limit),
  };
}

export async function getVendorUserDetailsWithServices(vendorUserId) {
  const vendorUser = await VendorUser.findById(vendorUserId).populate('userId').populate('categoryId');

  if (!vendorUser) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Vendor user not found');
  }

  const services = await VendorService.find({ vendorId: vendorUserId, isDeleted: { $ne: true } })
    .populate('serviceId')
    .populate('categoryId');

  const businessAddressUserId = (vendorUser.userId && vendorUser.userId._id) || vendorUser.userId;
  const businessAddress = await BusinessAddress.findOne({
    userId: businessAddressUserId,
    isDeleted: { $ne: true },
  });

  const va = await VendorAvailability.findOne({ vendorId: vendorUserId, isDeleted: { $ne: true } });

  const dayNames = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const todayDayName = dayNames[new Date().getDay()];

  const isOnline = va && va.isOnline !== undefined ? Boolean(va.isOnline) : true;
  const storeStatus = (va && va.storeStatus) || (isOnline ? 'online' : 'offline');
  const bookingOption = (va && va.bookingOption) || 'instant';
  const instantArrivalEstimate = (va && va.instantArrivalEstimate) || '30-40 mins';

  let isOpenToday = true;
  if (va && va.weeklySchedule && Array.isArray(va.weeklySchedule)) {
    const todaySchedule = va.weeklySchedule.find((s) => s.day && s.day.toLowerCase() === todayDayName);
    if (todaySchedule) {
      isOpenToday = Boolean(todaySchedule.isOpen);
    }
  }

  const isAvailable = isOnline && isOpenToday;

  let statusText = 'Available';
  let statusBadge = 'available';

  if (!isOnline) {
    statusText = 'Currently Unavailable';
    statusBadge = 'offline';
  } else if (!isOpenToday) {
    statusText = 'Closed Today';
    statusBadge = 'closed';
  } else if (bookingOption === 'instant') {
    statusText = `Arriving in ${instantArrivalEstimate}`;
    statusBadge = 'instant';
  } else {
    statusText = 'Open for Schedule';
    statusBadge = 'schedule';
  }

  const availabilityInfo = {
    isOnline,
    storeStatus,
    isOpenToday,
    isAvailable,
    statusText,
    statusBadge,
    bookingOption,
    instantArrivalEstimate,
    weeklySchedule: (va && va.weeklySchedule) || [],
  };

  return {
    vendorUser,
    businessAddress,
    services,
    vendorAvailability: availabilityInfo,
  };
}
