/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { VendorUser, User, Bank } from 'models';

export async function getVendorUserById(id, options = {}) {
  const vendorUser = await VendorUser.findById(id, options.projection, options);
  return vendorUser;
}

export async function getOne(query, options = {}) {
  const vendorUser = await VendorUser.findOne(query, options.projection, options);
  return vendorUser;
}

export async function getVendorUserList(filter, options = {}) {
  const vendorUser = await VendorUser.find(filter, options.projection, options);
  return vendorUser;
}

export async function getVendorUserListWithPagination(filter, options = {}) {
  const vendorUser = await VendorUser.paginate(filter, options);
  return vendorUser;
}

export async function createVendorUser(body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.bankDetailsId) {
    const bankDetailsId = await Bank.findOne({ _id: body.bankDetailsId });
    if (!bankDetailsId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bankDetailsId is not valid');
    }
  }
  const vendorUser = await VendorUser.create(body);
  return vendorUser;
}

export async function updateVendorUser(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  if (body.bankDetailsId) {
    const bankDetailsId = await Bank.findOne({ _id: body.bankDetailsId });
    if (!bankDetailsId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field bankDetailsId is not valid');
    }
  }
  const vendorUser = await VendorUser.findOneAndUpdate(filter, body, options);
  return vendorUser;
}

export async function updateManyVendorUser(filter, body, options = {}) {
  const vendorUser = await VendorUser.updateMany(filter, body, options);
  return vendorUser;
}

export async function removeVendorUser(filter) {
  const vendorUser = await VendorUser.findOneAndRemove(filter);
  return vendorUser;
}

export async function removeManyVendorUser(filter) {
  const vendorUser = await VendorUser.deleteMany(filter);
  return vendorUser;
}

export async function aggregateVendorUser(query) {
  const vendorUser = await VendorUser.aggregate(query);
  return vendorUser;
}

export async function aggregateVendorUserWithPagination(query, options = {}) {
  const aggregate = VendorUser.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const vendorUser = await VendorUser.aggregatePaginate(aggregate, options);
  return vendorUser;
}
