/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { VendorService, VendorUser, Services } from 'models';

export async function getVendorServiceById(id, options = {}) {
  const vendorService = await VendorService.findById(id, options.projection, options);
  return vendorService;
}

export async function getOne(query, options = {}) {
  const vendorService = await VendorService.findOne(query, options.projection, options);
  return vendorService;
}

export async function getVendorServiceList(filter, options = {}) {
  const vendorService = await VendorService.find(filter, options.projection, options);
  return vendorService;
}

export async function getVendorServiceListWithPagination(filter, options = {}) {
  const vendorService = await VendorService.paginate(filter, options);
  return vendorService;
}

export async function createVendorService(body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  const vendorService = await VendorService.create(body);
  return vendorService;
}

export async function updateVendorService(filter, body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  if (body.serviceId) {
    const serviceId = await Services.findOne({ _id: body.serviceId });
    if (!serviceId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field serviceId is not valid');
    }
  }
  const vendorService = await VendorService.findOneAndUpdate(filter, body, options);
  return vendorService;
}

export async function updateManyVendorService(filter, body, options = {}) {
  const vendorService = await VendorService.updateMany(filter, body, options);
  return vendorService;
}

export async function removeVendorService(filter) {
  const vendorService = await VendorService.findOneAndRemove(filter);
  return vendorService;
}

export async function removeManyVendorService(filter) {
  const vendorService = await VendorService.deleteMany(filter);
  return vendorService;
}

export async function aggregateVendorService(query) {
  const vendorService = await VendorService.aggregate(query);
  return vendorService;
}

export async function aggregateVendorServiceWithPagination(query, options = {}) {
  const aggregate = VendorService.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const vendorService = await VendorService.aggregatePaginate(aggregate, options);
  return vendorService;
}
