/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { VendorKyc, VendorUser } from 'models';

export async function getVendorKycById(id, options = {}) {
  const vendorKyc = await VendorKyc.findById(id, options.projection, options);
  return vendorKyc;
}

export async function getOne(query, options = {}) {
  const vendorKyc = await VendorKyc.findOne(query, options.projection, options);
  return vendorKyc;
}

export async function getVendorKycList(filter, options = {}) {
  const vendorKyc = await VendorKyc.find(filter, options.projection, options);
  return vendorKyc;
}

export async function getVendorKycListWithPagination(filter, options = {}) {
  const vendorKyc = await VendorKyc.paginate(filter, options);
  return vendorKyc;
}

export async function createVendorKyc(body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const vendorKyc = await VendorKyc.create(body);
  return vendorKyc;
}

export async function updateVendorKyc(filter, body, options = {}) {
  if (body.vendorId) {
    const vendorId = await VendorUser.findOne({ _id: body.vendorId });
    if (!vendorId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field vendorId is not valid');
    }
  }
  const vendorKyc = await VendorKyc.findOneAndUpdate(filter, body, options);
  return vendorKyc;
}

export async function updateManyVendorKyc(filter, body, options = {}) {
  const vendorKyc = await VendorKyc.updateMany(filter, body, options);
  return vendorKyc;
}

export async function removeVendorKyc(filter) {
  const vendorKyc = await VendorKyc.findOneAndRemove(filter);
  return vendorKyc;
}

export async function removeManyVendorKyc(filter) {
  const vendorKyc = await VendorKyc.deleteMany(filter);
  return vendorKyc;
}

export async function aggregateVendorKyc(query) {
  const vendorKyc = await VendorKyc.aggregate(query);
  return vendorKyc;
}

export async function aggregateVendorKycWithPagination(query, options = {}) {
  const aggregate = VendorKyc.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const vendorKyc = await VendorKyc.aggregatePaginate(aggregate, options);
  return vendorKyc;
}
