/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Wallet, User } from 'models';

export async function getWalletById(id, options = {}) {
  const wallet = await Wallet.findById(id, options.projection, options);
  return wallet;
}

export async function getOne(query, options = {}) {
  const wallet = await Wallet.findOne(query, options.projection, options);
  return wallet;
}

export async function getWalletList(filter, options = {}) {
  const wallet = await Wallet.find(filter, options.projection, options);
  return wallet;
}

export async function getWalletListWithPagination(filter, options = {}) {
  const wallet = await Wallet.paginate(filter, options);
  return wallet;
}

export async function createWallet(body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  const wallet = await Wallet.create(body);
  return wallet;
}

export async function updateWallet(filter, body, options = {}) {
  if (body.userId) {
    const userId = await User.findOne({ _id: body.userId });
    if (!userId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field userId is not valid');
    }
  }
  const wallet = await Wallet.findOneAndUpdate(filter, body, options);
  return wallet;
}

export async function updateManyWallet(filter, body, options = {}) {
  const wallet = await Wallet.updateMany(filter, body, options);
  return wallet;
}

export async function removeWallet(filter) {
  const wallet = await Wallet.findOneAndRemove(filter);
  return wallet;
}

export async function removeManyWallet(filter) {
  const wallet = await Wallet.deleteMany(filter);
  return wallet;
}

export async function aggregateWallet(query) {
  const wallet = await Wallet.aggregate(query);
  return wallet;
}

export async function aggregateWalletWithPagination(query, options = {}) {
  const aggregate = Wallet.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const wallet = await Wallet.aggregatePaginate(aggregate, options);
  return wallet;
}
