import express from 'express';
import userRoutes from './v1/user/user.route';
import addressRoutes from './v1/address/address.route';
import bankRoutes from './v1/bank/bank.route';
import vendorUserRoutes from './v1/vendorUser/vendorUser.route';
import vendorKycRoutes from './v1/vendorKyc/vendorKyc.route';
import categoriesRoutes from './v1/categories/categories.route';
import servicesRoutes from './v1/services/services.route';
import vendorServiceRoutes from './v1/vendorService/vendorService.route';
import bookingsRoutes from './v1/bookings/bookings.route';
import paymentsRoutes from './v1/payments/payments.route';
import reviewsRoutes from './v1/reviews/reviews.route';
import chatsRoutes from './v1/chats/chats.route';
import messagesRoutes from './v1/messages/messages.route';
import notificationsRoutes from './v1/notifications/notifications.route';
import supportTicketRoutes from './v1/supportTicket/supportTicket.route';
import walletRoutes from './v1/wallet/wallet.route';
import payoutsRoutes from './v1/payouts/payouts.route';
import couponsRoutes from './v1/coupons/coupons.route';
import bookingCouponsRoutes from './v1/bookingCoupons/bookingCoupons.route';
import vendorAvailabilityRoutes from './v1/vendorAvailability/vendorAvailability.route';
import bookingTrackingRoutes from './v1/bookingTracking/bookingTracking.route';
import favoriteVendorRoutes from './v1/favoriteVendor/favoriteVendor.route';
import authRoutes from './v1/auth/auth.route';

const router = express.Router();
router.use('/user', userRoutes);
router.use('/address', addressRoutes);
router.use('/bank', bankRoutes);
router.use('/vendorUser', vendorUserRoutes);
router.use('/vendorKyc', vendorKycRoutes);
router.use('/categories', categoriesRoutes);
router.use('/services', servicesRoutes);
router.use('/vendorService', vendorServiceRoutes);
router.use('/bookings', bookingsRoutes);
router.use('/payments', paymentsRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/chats', chatsRoutes);
router.use('/messages', messagesRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/supportTicket', supportTicketRoutes);
router.use('/wallet', walletRoutes);
router.use('/payouts', payoutsRoutes);
router.use('/coupons', couponsRoutes);
router.use('/bookingCoupons', bookingCouponsRoutes);
router.use('/vendorAvailability', vendorAvailabilityRoutes);
router.use('/bookingTracking', bookingTrackingRoutes);
router.use('/favoriteVendor', favoriteVendorRoutes);
router.use('/auth', authRoutes);
module.exports = router;
