/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userValidation = require('./user.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.addressValidation = require('./address.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.bankValidation = require('./bank.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.vendorUserValidation = require('./vendorUser.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.vendorKycValidation = require('./vendorKyc.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.categoriesValidation = require('./categories.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.servicesValidation = require('./services.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.vendorServiceValidation = require('./vendorService.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.bookingsValidation = require('./bookings.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.paymentsValidation = require('./payments.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.reviewsValidation = require('./reviews.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.chatsValidation = require('./chats.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.messagesValidation = require('./messages.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.notificationsValidation = require('./notifications.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.supportTicketValidation = require('./supportTicket.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.walletValidation = require('./wallet.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.payoutsValidation = require('./payouts.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.couponsValidation = require('./coupons.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.bookingCouponsValidation = require('./bookingCoupons.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.vendorAvailabilityValidation = require('./vendorAvailability.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.bookingTrackingValidation = require('./bookingTracking.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.favoriteVendorValidation = require('./favoriteVendor.validation');
