/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const BankSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    accountHoldername: {
      type: String,
    },
    bankName: {
      type: String,
    },
    accountNumber: {
      type: String,
    },
    ifscCode: {
      type: String,
    },
    branchName: {
      type: String,
    },
    upiId: {
      type: String,
    },
    accountType: {
      type: String,
      enum: Object.values(enumModel.EnumAccountTypeOfBank),
    },
    isDefault: {
      type: Boolean,
    },
    verificationStatus: {
      type: String,
      enum: Object.values(enumModel.EnumVerificationStatusOfBank),
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
BankSchema.plugin(toJSON);
BankSchema.plugin(mongoosePaginateV2);
BankSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const BankModel = mongoose.models.Bank || mongoose.model('Bank', BankSchema, 'Bank');
module.exports = BankModel;
