/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const pointSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: Object.values(enumModel.EnumTypeOfPoint),
    default: enumModel.EnumTypeOfPoint.POINT,
    required: true,
  },
  coordinates: {
    type: [Number],
    required: true,
  },
});
const BookingTrackingSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bookings',
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumStatusOfBookingTracking),
    },
    location: {
      type: pointSchema,
    },
    note: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
BookingTrackingSchema.plugin(toJSON);
BookingTrackingSchema.plugin(mongoosePaginateV2);
BookingTrackingSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const BookingTrackingModel =
  mongoose.models.BookingTracking || mongoose.model('BookingTracking', BookingTrackingSchema, 'BookingTracking');
module.exports = BookingTrackingModel;
