/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const BookingsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: String,
    },
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    serviceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Services',
    },
    vendorServiceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorService',
    },
    addressId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Address',
    },
    bookingDate: {
      type: Date,
    },
    bookingTime: {
      type: String,
    },
    serviceStartTime: {
      type: Date,
    },
    serviceEndTime: {
      type: Date,
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumStatusOfBookings),
    },
    cancelReason: {
      type: String,
    },
    subtotal: {
      type: Number,
    },
    serviceFee: {
      type: Number,
    },
    tax: {
      type: Number,
    },
    totalAmount: {
      type: Number,
    },
    paymentStatus: {
      type: String,
      enum: Object.values(enumModel.EnumPaymentStatusOfBookings),
    },
    paymentMethod: {
      type: String,
    },
    otp: {
      type: String,
    },
    notes: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
BookingsSchema.plugin(toJSON);
BookingsSchema.plugin(mongoosePaginateV2);
BookingsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const BookingsModel = mongoose.models.Bookings || mongoose.model('Bookings', BookingsSchema, 'Bookings');
module.exports = BookingsModel;
