/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const BookingCouponsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bookings',
    },
    couponId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Coupons',
    },
    discountAmount: {
      type: Number,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
BookingCouponsSchema.plugin(toJSON);
BookingCouponsSchema.plugin(mongoosePaginateV2);
BookingCouponsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const BookingCouponsModel =
  mongoose.models.BookingCoupons || mongoose.model('BookingCoupons', BookingCouponsSchema, 'BookingCoupons');
module.exports = BookingCouponsModel;
