/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const CouponsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    code: {
      type: String,
    },
    title: {
      type: String,
    },
    discountType: {
      type: String,
    },
    discountValue: {
      type: String,
    },
    minOrderAmount: {
      type: String,
    },
    maxDiscount: {
      type: String,
    },
    startDate: {
      type: Date,
    },
    endDate: {
      type: Date,
    },
    usageLimit: {
      type: String,
    },
    isActive: {
      type: Boolean,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
CouponsSchema.plugin(toJSON);
CouponsSchema.plugin(mongoosePaginateV2);
CouponsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const CouponsModel = mongoose.models.Coupons || mongoose.model('Coupons', CouponsSchema, 'Coupons');
module.exports = CouponsModel;
