/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const EnumRoleOfUser = {
  CUSTOMER: 'customer',
  VENDOR: 'vendor',
  ADMIN: 'admin',
};
const EnumCodeTypeOfCode = {
  RESETPASSWORD: 'resetPassword',
  LOGIN: 'login',
};
const EnumPlatformOfDeviceToken = {
  ANDROID: 'android',
  IOS: 'ios',
  WEB: 'web',
};
const EnumLocationTypeOfAddress = {
  HOME: 'home',
  WORK: 'work',
  HOTEL: 'hotel',
  OTHER: 'other',
};
const EnumAccountTypeOfBank = {
  SAVING: 'saving',
  CURRENT: 'current',
};
const EnumVerificationStatusOfBank = {
  VERIFIED: 'verified',
  PANDING: 'panding',
  REJECTED: 'rejected',
};
const EnumKycStatusOfVendorUser = {
  PANDIG: 'pandig',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};
const EnumStatusOfVendorKyc = {
  PANDING: 'panding',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};
const EnumStatusOfBookings = {
  PANDING: 'panding',
  ACCEPTED: 'accepted',
  ONTHEWAY: 'ontheway',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
};
const EnumPaymentStatusOfBookings = {
  PANDING: 'panding',
  PAID: 'paid',
  FAILED: 'failed',
  REFUNDED: 'refunded',
};
const EnumPaymentGatewayOfPayments = {
  RAZORPAY: 'razorpay',
  CASHFREE: 'cashfree',
};
const EnumPaymentStatusOfPayments = {
  PANDING: 'panding',
  PAID: 'paid',
  FAILED: 'failed',
  REFUNDED: 'refunded',
};
const EnumRefundStatusOfPayments = {
  NONE: 'none',
  PARTIALY: 'partialy',
  FULL: 'full',
};
const EnumMessageTypeOfMessages = {
  TEXT: 'text',
  IMAGE: 'image',
  FILE: 'file',
};
const EnumStatusOfSupportTicket = {
  OPEN: 'open',
  INPROGRESS: 'inprogress',
  RESOLVED: 'resolved',
  CLOSED: 'closed',
};
const EnumRoleOfWallet = {
  VENDOR: 'vendor',
  ADMIN: 'admin',
  CUSTOMER: 'customer',
};
const EnumStatusOfPayouts = {
  PANDING: 'panding',
  PAID: 'paid',
  FAILED: 'failed',
};
const EnumStatusOfBookingTracking = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  VENDOR_ON_THE_WAY: 'vendorOnTheWay',
  ARRIVED: 'arrived',
  STARTED: 'started',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
};
const EnumTypeOfPoint = {
  POINT: 'point',
};
const EnumTypeOfToken = {
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
  REFRESH: 'refresh',
};
module.exports = {
  EnumRoleOfUser,
  EnumCodeTypeOfCode,
  EnumPlatformOfDeviceToken,
  EnumLocationTypeOfAddress,
  EnumAccountTypeOfBank,
  EnumVerificationStatusOfBank,
  EnumKycStatusOfVendorUser,
  EnumStatusOfVendorKyc,
  EnumStatusOfBookings,
  EnumPaymentStatusOfBookings,
  EnumPaymentGatewayOfPayments,
  EnumPaymentStatusOfPayments,
  EnumRefundStatusOfPayments,
  EnumMessageTypeOfMessages,
  EnumStatusOfSupportTicket,
  EnumRoleOfWallet,
  EnumStatusOfPayouts,
  EnumStatusOfBookingTracking,
  EnumTypeOfPoint,
  EnumTypeOfToken,
};
