/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.User = require('./user.model');
module.exports.Address = require('./address.model');
module.exports.BusinessAddress = require('./businessAddress.model');
module.exports.Bank = require('./bank.model');
module.exports.VendorUser = require('./vendorUser.model');
module.exports.VendorKyc = require('./vendorKyc.model');
module.exports.Categories = require('./categories.model');
module.exports.Services = require('./services.model');
module.exports.VendorService = require('./vendorService.model');
module.exports.Bookings = require('./bookings.model');
module.exports.Payments = require('./payments.model');
module.exports.Reviews = require('./reviews.model');
module.exports.Chats = require('./chats.model');
module.exports.Messages = require('./messages.model');
module.exports.Notifications = require('./notifications.model');
module.exports.SupportTicket = require('./supportTicket.model');
module.exports.Wallet = require('./wallet.model');
module.exports.Payouts = require('./payouts.model');
module.exports.Coupons = require('./coupons.model');
module.exports.BookingCoupons = require('./bookingCoupons.model');
module.exports.VendorAvailability = require('./vendorAvailability.model');
module.exports.BookingTracking = require('./bookingTracking.model');
module.exports.FavoriteVendor = require('./favoriteVendor.model');
module.exports.Token = require('./token.model');
module.exports.TempS3 = require('./tempS3.model');
module.exports.Error = require('./error.model');
module.exports.Enum = require('./enum.model');
module.exports.plugins = require('./plugins');
module.exports.CountryCode = require('./countryCode.model');
