/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const MessagesSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    chatId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Chats',
    },
    senderId: {
      type: mongoose.Mixed,
    },
    message: {
      type: String,
    },
    messageType: {
      type: String,
      enum: Object.values(enumModel.EnumMessageTypeOfMessages),
    },
    isRead: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
MessagesSchema.plugin(toJSON);
MessagesSchema.plugin(mongoosePaginateV2);
MessagesSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const MessagesModel = mongoose.models.Messages || mongoose.model('Messages', MessagesSchema, 'Messages');
module.exports = MessagesModel;
