/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const PaymentsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bookings',
    },
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    amount: {
      type: Number,
    },
    transactionId: {
      type: String,
    },
    paymentGateway: {
      type: String,
      enum: Object.values(enumModel.EnumPaymentGatewayOfPayments),
    },
    paymentStatus: {
      type: String,
      enum: Object.values(enumModel.EnumPaymentStatusOfPayments),
    },
    adminCommission: {
      type: Number,
    },
    vendorAmount: {
      type: Number,
    },
    refundStatus: {
      type: String,
      enum: Object.values(enumModel.EnumRefundStatusOfPayments),
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
PaymentsSchema.plugin(toJSON);
PaymentsSchema.plugin(mongoosePaginateV2);
PaymentsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const PaymentsModel = mongoose.models.Payments || mongoose.model('Payments', PaymentsSchema, 'Payments');
module.exports = PaymentsModel;
