/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const PayoutsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    walletId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Wallet',
    },
    amount: {
      type: Number,
    },
    utrTransactionId: {
      type: String,
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumStatusOfPayouts),
    },
    requestedAt: {
      type: Date,
    },
    paidAt: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
PayoutsSchema.plugin(toJSON);
PayoutsSchema.plugin(mongoosePaginateV2);
PayoutsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const PayoutsModel = mongoose.models.Payouts || mongoose.model('Payouts', PayoutsSchema, 'Payouts');
module.exports = PayoutsModel;
