/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const ReviewsSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bookings',
    },
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    rating: {
      type: Number,
    },
    review: {
      type: String,
    },
    vendorReply: {
      type: String,
    },
    vendorRepliedAt: {
      type: Date,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
ReviewsSchema.plugin(toJSON);
ReviewsSchema.plugin(mongoosePaginateV2);
ReviewsSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
ReviewsSchema.index({ vendorId: 1, isDeleted: 1, createdAt: -1 });
ReviewsSchema.index({ customerId: 1, isDeleted: 1, createdAt: -1 });
ReviewsSchema.index({ bookingId: 1, isDeleted: 1 });

const ReviewsModel = mongoose.models.Reviews || mongoose.model('Reviews', ReviewsSchema, 'Reviews');
module.exports = ReviewsModel;
