/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const SupportTicketSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bookings',
    },
    issueType: {
      type: String,
    },
    message: {
      type: String,
    },
    images: {
      type: [String],
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumStatusOfSupportTicket),
    },
    adminReply: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
SupportTicketSchema.plugin(toJSON);
SupportTicketSchema.plugin(mongoosePaginateV2);
SupportTicketSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const SupportTicketModel =
  mongoose.models.SupportTicket || mongoose.model('SupportTicket', SupportTicketSchema, 'SupportTicket');
module.exports = SupportTicketModel;
