import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON } from 'models/plugins';
import enumModel from 'models/enum.model';
import bcrypt from 'bcryptjs';
import { normalizeS3ProfileUrl } from 'utils/common';
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const OauthSchema = new mongoose.Schema({
  id: {
    type: String,
  },
  token: {
    type: String,
  },
});
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const CodeSchema = new mongoose.Schema({
  code: {
    type: String,
  },
  expirationDate: {
    type: Date,
  },
  used: {
    type: Boolean,
  },
  codeType: {
    type: String,
    enum: Object.values(enumModel.EnumCodeTypeOfCode),
  },
});
const UserImagesSchema = new mongoose.Schema(
  {
    url: {
      type: String,
    },
    name: {
      type: String,
    },
    isDeleted: Boolean,
    deleted: Boolean,
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
const DeviceTokenSchema = new mongoose.Schema({
  /**
   *Device Token Of User
   * */
  deviceToken: {
    type: String,
  },
  /**
   *Platform of User
   * */
  platform: {
    type: String,
    enum: Object.values(enumModel.EnumPlatformOfDeviceToken),
  },
});
const UserSchema = new mongoose.Schema({
  /**
   * Name of User
   * */
  name: {
    type: String,
  },
  /**
   * Email address of User
   * */
  email: {
    type: String,
    // eslint-disable-next-line security/detect-unsafe-regex
    match: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
  },
  /**
   * For email verification
   * */
  emailVerified: {
    type: Boolean,
    private: true,
  },
  /**
   * role
   * */
  role: {
    type: String,
    enum: Object.values(enumModel.EnumRoleOfUser),
    default: enumModel.EnumRoleOfUser.CUSTOMER,
  },
  /**
   * Google based authentication
   * */
  googleProvider: {
    type: OauthSchema,
  },
  /**
   * custom server authentication
   * */
  codes: {
    type: [CodeSchema],
  },
  /**
   * password for authentication
   * */
  password: {
    type: String,
    private: true,
  },
  /**
   * To store device tokens
   * */
  deviceTokens: {
    type: [DeviceTokenSchema],
  },
  /**
   * apple based authentication
   * */
  appleProvider: {
    type: OauthSchema,
  },
  /**
   * facebook based authentication
   * */
  facebookProvider: {
    type: OauthSchema,
  },
  businessName: {
    type: String,
  },
  mobileNumber: {
    type: Number,
  },
  countryCode: {
    type: String,
  },
  isDeleted: {
    type: Boolean,
  },
  fullName: {
    type: String,
  },
  profileImage: {
    type: String,
  },
  currentLocation: {
    type: String,
  },
  pendingEmail: {
    type: String,
    private: true,
  },
  pendingMobileNumber: {
    type: Number,
    private: true,
  },
  pendingCountryCode: {
    type: String,
    private: true,
  },
  userProfilePic: [UserImagesSchema],
  profilePic: {
    type: String,
  },
  location: {
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point',
    },
    coordinates: {
      type: [Number],
    },
  },
});
UserSchema.index({ location: '2dsphere' });
UserSchema.plugin(toJSON);
UserSchema.plugin(mongoosePaginateV2);
/**
 * Check if email is taken
 * @param {string} email - The user's email
 * @param {ObjectId} [excludeUserId] - The id of the User to be excluded
 * @returns Promise with boolean value
 */
UserSchema.statics.isEmailTaken = async function (email, excludeUserId) {
  const User = await this.findOne({ email, _id: { $ne: excludeUserId } });
  return !!User;
};
UserSchema.statics.isMobileNumberTaken = async function (mobileNumber, excludeUserId) {
  const user = await this.findOne({ mobileNumber, _id: { $ne: excludeUserId } });
  return !!user;
};

UserSchema.pre('save', async function (next) {
  const User = this;
  if (User.isModified('password')) {
    User.password = await bcrypt.hash(User.password, 8);
  }
  if (User.location && (!User.location.coordinates || User.location.coordinates.length === 0)) {
    User.location = undefined;
  }
  if (User.profilePic) {
    User.profilePic = normalizeS3ProfileUrl(User.profilePic);
  }
  if (User.profileImage) {
    User.profileImage = normalizeS3ProfileUrl(User.profileImage);
  }
  if (User.profilePic && !User.profileImage) {
    User.profileImage = User.profilePic;
  }
  if (User.profileImage && !User.profilePic) {
    User.profilePic = User.profileImage;
  }
  if (Array.isArray(User.userProfilePic)) {
    User.userProfilePic.forEach((img) => {
      if (img && img.url) {
        // eslint-disable-next-line no-param-reassign
        img.url = normalizeS3ProfileUrl(img.url);
      }
    });
  }
  next();
});

/* eslint-disable no-param-reassign */
const sanitizeUserUpdate = async (update) => {
  if (!update) return;
  if (update.password) {
    const passwordHash = await bcrypt.hash(update.password, 10);
    // eslint-disable-next-line no-param-reassign
    update.password = passwordHash;
  }
  const target = update.$set || update;
  if (target.profilePic) {
    target.profilePic = normalizeS3ProfileUrl(target.profilePic);
  }
  if (target.profileImage) {
    target.profileImage = normalizeS3ProfileUrl(target.profileImage);
  }
  if (target.profilePic && target.profileImage === undefined) {
    target.profileImage = target.profilePic;
  }
  if (target.profileImage && target.profilePic === undefined) {
    target.profilePic = target.profileImage;
  }
  if (Array.isArray(target.userProfilePic)) {
    target.userProfilePic.forEach((img) => {
      if (img && img.url) {
        // eslint-disable-next-line no-param-reassign
        img.url = normalizeS3ProfileUrl(img.url);
      }
    });
  }
  if (update.$addToSet && update.$addToSet.userProfilePic && update.$addToSet.userProfilePic.url) {
    update.$addToSet.userProfilePic.url = normalizeS3ProfileUrl(update.$addToSet.userProfilePic.url);
  }
};

/**
 * When user reset password or change password then it save in bcrypt format
 */
UserSchema.pre(['findOneAndUpdate', 'updateOne'], async function (next) {
  const update = this.getUpdate();
  if (update) {
    await sanitizeUserUpdate(update);
  }
  next();
});

UserSchema.post(
  ['find', 'findOne', 'findOneAndUpdate', 'findOneAndDelete', 'findOneAndRemove', 'update', 'updateOne', 'updateMany'],
  function (result, next) {
    const sanitizeUserDoc = (doc) => {
      if (!doc) return;
      if (doc.profilePic) {
        // eslint-disable-next-line no-param-reassign
        doc.profilePic = normalizeS3ProfileUrl(doc.profilePic);
      }
      if (doc.profileImage) {
        // eslint-disable-next-line no-param-reassign
        doc.profileImage = normalizeS3ProfileUrl(doc.profileImage);
      }
      if (doc.profilePic && !doc.profileImage) {
        // eslint-disable-next-line no-param-reassign
        doc.profileImage = doc.profilePic;
      }
      if (doc.profileImage && !doc.profilePic) {
        // eslint-disable-next-line no-param-reassign
        doc.profilePic = doc.profileImage;
      }
      if (doc.userProfilePic && doc.userProfilePic.length) {
        // eslint-disable-next-line no-param-reassign
        doc.userProfilePic = doc.userProfilePic.filter((d) => !d.isDeleted && !d.deleted);
        doc.userProfilePic.forEach((d) => {
          if (d && d.url) {
            // eslint-disable-next-line no-param-reassign
            d.url = normalizeS3ProfileUrl(d.url);
          }
        });
      }
    };

    if (Array.isArray(result)) {
      result.forEach(sanitizeUserDoc);
    } else if (result) {
      sanitizeUserDoc(result);
    }

    next(null, result);
  }
);
const UserModel = mongoose.models.User || mongoose.model('User', UserSchema, 'User');
module.exports = UserModel;
