/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const VendorAvailabilitySchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    day: {
      type: Number,
    },
    startTime: {
      type: Date,
    },
    endTime: {
      type: Date,
    },
    isAvailable: {
      type: Boolean,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
VendorAvailabilitySchema.plugin(toJSON);
VendorAvailabilitySchema.plugin(mongoosePaginateV2);
VendorAvailabilitySchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const VendorAvailabilityModel =
  mongoose.models.VendorAvailability || mongoose.model('VendorAvailability', VendorAvailabilitySchema, 'VendorAvailability');
module.exports = VendorAvailabilityModel;
