/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const VendorKycSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    documentType: {
      type: String,
    },
    documentFront: {
      type: String,
    },
    documentBack: {
      type: String,
    },
    selfieVideo: {
      type: String,
    },
    status: {
      type: String,
      enum: Object.values(enumModel.EnumStatusOfVendorKyc),
      default: enumModel.EnumStatusOfVendorKyc.PANDING,
    },
    rejectedReason: {
      type: String,
    },
    verifiedBy: {
      type: mongoose.Mixed,
      required: true,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
VendorKycSchema.plugin(toJSON);
VendorKycSchema.plugin(mongoosePaginateV2);
VendorKycSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const VendorKycModel = mongoose.models.VendorKyc || mongoose.model('VendorKyc', VendorKycSchema, 'VendorKyc');
module.exports = VendorKycModel;
