/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const VendorUserSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    businessName: {
      type: String,
    },
    gstNumber: {
      type: String,
    },
    description: {
      type: String,
    },
    experience: {
      type: Number,
    },
    rating: {
      type: Number,
    },
    totalReviews: {
      type: Number,
    },
    /**
     * km
     * */
    serviceRadius: {
      type: Number,
    },
    isKycVerified: {
      type: Boolean,
    },
    kycStatus: {
      type: String,
      enum: Object.values(enumModel.EnumKycStatusOfVendorUser),
    },
    bankDetailsId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bank',
    },
    profileCompleted: {
      type: Boolean,
    },
    avgResponseTime: {
      type: String,
    },
    completedBookings: {
      type: Number,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
VendorUserSchema.plugin(toJSON);
VendorUserSchema.plugin(mongoosePaginateV2);
VendorUserSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const VendorUserModel = mongoose.models.VendorUser || mongoose.model('VendorUser', VendorUserSchema, 'VendorUser');
module.exports = VendorUserModel;
