/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const VendorServiceSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'VendorUser',
    },
    serviceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Services',
    },
    price: {
      type: Number,
    },
    /**
     * minutes
     * */
    estimatedTime: {
      type: Number,
    },
    isAvailable: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
VendorServiceSchema.plugin(toJSON);
VendorServiceSchema.plugin(mongoosePaginateV2);
VendorServiceSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const VendorServiceModel =
  mongoose.models.VendorService || mongoose.model('VendorService', VendorServiceSchema, 'VendorService');
module.exports = VendorServiceModel;
